### ISSUE TITLE
Use Presentation API

### ISSUE THREAD

**Issue by jxnblk** [jxnblk/mdx-deck#1]
https://developer.mozilla.org/en-US/docs/Web/API/Presentation_API

**Comment by jxnblk** [comment]
Seems like this might only work the ChromeCast devices at the moment? Might not be worth the effort of getting a test device to try this out

**Comment by SaraVieira** [comment]
Hey !

Where did you see this works on chromecast?

I have one I can test this out :)

**Comment by jxnblk** [comment]
Hey, sorry for the delay! I only looked into this briefly, but learned some from checking out this if you feel like digging in: https://github.com/FormidableLabs/spectacle/pull/561

Maybe it does work with other displays, but didn’t spend too much time on it
