### ISSUE TITLE
Add support for og meta tags

### ISSUE THREAD

**Issue by broccolini** [jxnblk/mdx-deck#100]
Would be rad to be able to add og metadata for sharing on twitter and such!

**Comment by tomByrer** [comment]
Maybe you could just make a component?

**Comment by jxnblk** [comment]
Yeah, I'm working on a `<Head />` component that you can use directly in MDX – similar to react-helmet etc, but custom tailored for mdx-deck

**Comment by tomByrer** [comment]
I'm glad you got a `<head>`-start on this suggestion then!
