### ISSUE TITLE
addEventListener dont work

### ISSUE THREAD

**Issue by emersonlaurentino** [jxnblk/mdx-deck#102]
When there is an `anchor` tag on the slide and it is focused, the right and left key events no longer work.

Can you check: https://github-ds.now.sh/#28 (click on link and try move to other slide pressing right or left key).

I use this browser:
![screenshot from 2018-08-12 10-18-38](https://user-images.githubusercontent.com/10627086/44002457-26361e2a-9e19-11e8-9bcc-8f48985530f2.png)

**Comment by jxnblk** [comment]
Keyboard shortcuts only work when there isn’t a focused element. This is by design so that any react component should work as expected
