### ISSUE TITLE
Suggestion: Use first slides's <h1> as HTML's <title>

### ISSUE THREAD

**Issue by tomByrer** [jxnblk/mdx-deck#103]
We programmers are lazy; DRY, don't RTFM, & stuff.

Open to using the entire first slide's text as `<title>`, with CLI `--title` as overried.

**Comment by jxnblk** [comment]
Coming in v3 #392

**Comment by flexbox** [comment]
Hey @tomByrer Your issue is solved 🎉 
Can you close it 🙏 ?
