### ISSUE TITLE
Code zooming transitions

### ISSUE THREAD

**Issue by kutyel** [jxnblk/mdx-deck#104]
Hi! This repo is great, and I'm incredibly looking forward to use it for my [next presentation](http://reactalicante.es/)! 😄 

The thing is, I want to achieve the effect I saw in this [talk](https://www.youtube.com/watch?v=_MAD4Oly9yg) where you are actually showing code, but zooming in some parts and just scrolling from top to bottom. Is there any easy (or maybe _built-in_) option that I don't know of to do this? I know some people use Spectacle.js for that but I think this is way easier! 😊

Thanks in advance and keep up the good work! 😎 

---

**EDIT:** Added gif for reference 😉 (thanks @trevordmiller)

![code](https://user-images.githubusercontent.com/5497885/44323887-eef0f180-a410-11e8-975e-4c7fb6b3c901.gif)

**Comment by jxnblk** [comment]
Probably related to #5; I think the library you mention might be https://github.com/jamiebuilds/spectacle-code-slide which I’d love to support in this library, but I haven’t spent time looking at how to make spectacle components work yet

**Comment by pomber** [comment]
I'm currently working on something similar to (forked from) spectacle-code-slide and I would like to make it work with mdx-deck.  
But I'm not sure how to access `deck` and `slide` like `Appear` does. `withDeck` and `withSlide` aren't exported in `src/index.js`. Any other way to access them from the npm package?

**Comment by jxnblk** [comment]
If those HOCs aren’t exported, that’s an oversight – ideally they’d be one HOC but that’d require some architectural changes

**Comment by pomber** [comment]
My bad. I can import them from: 
```js
import { withDeck } from "mdx-deck/dist/context";
import { withSlide } from "mdx-deck/dist/Slide";
```

**Comment by pomber** [comment]
I have something working https://angry-sinoussi-d4c063.netlify.com/. It isn't ready yet, I'll try to publish it after I use it for a talk next week.

**Comment by kutyel** [comment]
Wow, that looks very promising!! I think you almost got it! 🎉 @jxnblk what do you think? 😄

**Comment by trevordmiller** [comment]
Nice work @pomber! Can't wait for this to land in mdx-deck.

**Comment by pomber** [comment]
Anyone wants to test it? It's here https://github.com/pomber/code-surfer

**Comment by trevordmiller** [comment]
@pomber Awesome. I’ll be testing it in the next couple of days. On mobile now glancing over it and it looks great - would be nice to A) expose theming options and B) improve mobile though.

@jxnblk, what do you think about wrapping this as a [mdx-deck exported component](https://github.com/jxnblk/mdx-deck/blob/master/docs/components.md) - maybe called `FocusCode` or something to match `FullScreenCode`?

**Comment by jxnblk** [comment]
CodeSurfer looks great! I think we can add a link to the readme for code-surfer to close this issue out

**Comment by kutyel** [comment]
Closing this since now **code-surfer** exists and the link is on readme.md, thanks! 🎉
