### ISSUE TITLE
Disable swipe on desktop

### ISSUE THREAD

**Issue by kentcdodds** [jxnblk/mdx-deck#111]
If I'm selecting text during my talk, mdx-deck interprets that as a swipe and goes forward to the next slide:

![kapture 2018-08-15 at 8 54 22](https://user-images.githubusercontent.com/1500684/44154840-ec496508-a068-11e8-9ecd-266b9ff0dc5f.gif)

**Comment by jxnblk** [comment]
Should be fixed in v1.6.3

**Comment by kentcdodds** [comment]
Thank you!
