### ISSUE TITLE
Feature request: code block step through

### ISSUE THREAD

**Issue by trevordmiller** [jxnblk/mdx-deck#118]
First, thanks so much for such a great tool! It’s been very helpful :)

Second, would it be possible / desired to have a code revealing walkthrough option? Like this: 

![d8f5db18-6351-4cd3-b95e-f7a787db6651](https://user-images.githubusercontent.com/5497885/44323887-eef0f180-a410-11e8-975e-4c7fb6b3c901.gif)

From https://github.com/jamiebuilds/spectacle-code-slide

I personally think this is very useful for digesting code snippets. For example, a talk at React Rally this past week that used this:
https://github.com/joshwcomeau/explorable-explanations-with-react

**Comment by trevordmiller** [comment]
Column control seems a bit much/ complicated - but if it were only by lines, maybe a custom divider syntax could be added to the normal code block backtick syntax to enable this? `—-` already divides slides automatically so maybe something like `~~~` could be used inside backtick codeblocks to enable code revealing by line ranges?

But no problem if this is out of scope or too complicated, I like how simple mdx-deck is and don’t want to over complicate it - there are plenty of other slide tools for that ;)

Thanks again!

**Comment by trevordmiller** [comment]
Looks like this might be a duplicate of https://github.com/jxnblk/mdx-deck/issues/104#thread-subscription-status. Feel free to close if that is the case :)

**Comment by kutyel** [comment]
It is definitely a duplicate 😉 The only difference is that you actually found the spectacle plugin 😂
