### ISSUE TITLE
Appear: Missing Props

### ISSUE THREAD

**Issue by felixheck** [jxnblk/mdx-deck#119]
Hi there – just started with `mdx-deck`.
It's awesome, thanks!

But having some issues with using `Appear`.
As soon as use the component the following errors occur and the app breaks.

```
Warning: Failed prop type: The prop `slide` is marked as required in `Appear`, but its value is `null`.
```

```
Warning: Failed prop type: The prop `deck` is marked as required in `Appear`, but its value is `null`.
```

Haven't found any hint in the docs.

--- 

**env**
`npm`: 6.2.0  
`node`: 10.9.0  
`@mdx-js/mdx`: 0.15.0  
`mdx-deck`: 1.6.4

**Comment by jxnblk** [comment]
Those are just warnings, but is the app not working either?

**Comment by felixheck** [comment]
There are some errors, I assumed those are due to the warnings. Anyway:

![image](https://user-images.githubusercontent.com/14093205/44384961-4b8e0280-a51e-11e8-870e-25e2a8524fe0.png)

**Comment by felixheck** [comment]
@jxnblk can you provide the source code of the demo? just to check if I'm doing anything wrong..

**Comment by jxnblk** [comment]
What demo are you referring to? All the source code for this repo is in the repo...

**Comment by felixheck** [comment]
https://jxnblk.com/mdx-deck/#9

this one — just found the build app in the `gh-pages` branches but not the underlying .mdx files

**Comment by felixheck** [comment]
The bug occurs when using `mdx-deck` even in the demo — it works when using `../dist` instead

**Comment by jxnblk** [comment]
I suspect that this might be related to a bug that #144 is attempting to fix. See also pomber/code-surfer#8

**Comment by felixheck** [comment]
Yep, seems so

**Comment by jxnblk** [comment]
Just published `v1.7.0` – let me know if that resolves the issues you were seeing

**Comment by felixheck** [comment]
![image](https://user-images.githubusercontent.com/14093205/44867250-9c70ca00-ac87-11e8-8f6f-9dfbf2dfe8af.png)


:(

**Comment by jxnblk** [comment]
Sorry, I’m really not sure what’s happening. Can you try `rm -rf node_modules && npm i` and try running it on a new mdx file with just a heading and no imports?

**Comment by felixheck** [comment]
Well it works without the `Appear` component.
Even this minimal working example does not work:

https://gist.github.com/felixheck/7a2a41c53c07ff68a8eda79060cd713d

**Comment by felixheck** [comment]
![image](https://user-images.githubusercontent.com/14093205/46286293-fa424b80-c57e-11e8-8c3e-424869d811fa.png)

Getting the same errors again with several versions..

**Comment by jxnblk** [comment]
Closing this since the internals for v2 are quite different and this *should* be resolved
