### ISSUE TITLE
PDF export ignores Appear component

### ISSUE THREAD

**Issue by zcei** [jxnblk/mdx-deck#121]
Hej,

I've been successfully using `mdx-deck` for my latest presentation, and it was a breeze! 🙏 
Now I wanted to export it as a PDF in order to upload it.

## The Problem

List elements (and potentially everything else) in `<Appear />` is not rendered.

## Expected Behavior

Every component in `<Appear />` with index `n` yields a new page that renders all components up to and including index `n`.

## How to reproduce?

```mdx
import { Appear } from 'mdx-deck'

# I don't see the problem?

<ul>
  <Appear>
    <li>Not</li>
    <li>in</li>
    <li>PDF</li>
  </Appear>
</ul>
---
# The end
```

```sh
mdx-deck pdf pdf-issue.mdx
```

Open `dist/presentation.pdf`. It has only two pages, expected are five pages.

**Comment by hxuanhung** [comment]
Any idea on how to takcle this? I can work on it.

**Comment by jxnblk** [comment]
I suspect there's two primary ways: 

1. An explicit prop passed through context to the Appear component
2. Refactor Appear to use styled-components and a `@media print` rule to control visibility

If you wanna try it out in a PR, I'd be happy to look, but I haven't had time to investigate this myself

**Comment by hxuanhung** [comment]
👍, I will try out in a PR

**Comment by hxuanhung** [comment]
Hi, I've just fired a PR for it here #186. I simply launch Puppeteer with a specigic user-agent and check it in Appear.

**Comment by zcei** [comment]
Done in https://github.com/jxnblk/mdx-deck/pull/186
