### ISSUE TITLE
PDF exits with error when the output file doesn't exits

### ISSUE THREAD

**Issue by gillchristian** [jxnblk/mdx-deck#123]
## Output

```
$ yarn mdx-deck pdf deck.mdx
[mdx-deck] exporting to PDF
[mdx-deck] rendering PDF
[err] { Error: ENOENT: no such file or directory, open '/home/gillchristian/dev/ha/mui-deck/dist/presentation.pdf'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/gillchristian/dev/ha/mui-deck/dist/presentation.pdf' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Expected output

`mdx-deck pdf` script should create the out file if it doesn't exist.

## How to reproduce

- Create a mdx-deck project
- Run `yarn mdx-deck pdf deck.mdx`

---

Unless this is expected (I guess not) I'm up for working on a solution.

**Comment by gillchristian** [comment]
Btw, I worked our this by creating the file before building pdf.

```json
"scripts": {
  "pdf": "touch presentation.pdf && mdx-deck pdf deck.mdx -d ."
}
```

**Comment by jxnblk** [comment]
I can't reproduce this locally. Are you using `npm run pdf` in the second example? Could it be something screwy that `yarn` is doing in the first example?

**Comment by jxnblk** [comment]
Also, it could be helpful to know what version of node and npm you have installed

**Comment by gillchristian** [comment]
I didn't run with `npm` the first time. Now I tried again and it fails when the directory is not existing (default is `dist/` so it fails for it) for both `npm` and `yarn`.

This works:

```
mdx-deck pdf deck.mdx -d .
```

These don't (when directory doesn't exist):

```
mdx-deck pdf deck.mdx
mdx-deck pdf deck.mdx -d foo
```

---

```
$ node -v
v8.11.2

$ npm -v
5.6.0

$ yarn -v
1.7.0
```

**Comment by jxnblk** [comment]
Really not sure why this doesn't work on your setup. Might be worth looking at the [Puppeteer Issues](https://github.com/Googlechrome/puppeteer/issues?utf8=✓&q=is%3Aissue+pdf+no+such+file+or+directory), which the PDF export [uses](https://github.com/jxnblk/mdx-deck/blob/master/lib/pdf.js), to see if that helps.

**Comment by gillchristian** [comment]
#135 should fixed it. Thanks!
