### ISSUE TITLE
Static Display aspect ratio 4:3 or 16:9

### ISSUE THREAD

**Issue by kabl** [jxnblk/mdx-deck#124]
# Description

When I change my browsers width or height the layout (resp. the ratio is changing). That means the rendering of the presentation changes.

It would be great to have a container in the browser with a fix ratio. Such as 4:3 or 16:9. Which will not change based on the browsers size. Of course when changing the browser size the presentations size will increase or decrease but the ratio will remain same. 

# Reproduce
```
./cli.js docs/index.mdx
```
- third last slide - inline image. 
- Make the browser small. Text "inline image" will be moved out of the visible space.

**Comment by jxnblk** [comment]
Thanks! I could see this being an optional component/setting, but I think the default layout should be a responsive web-like layout

**Comment by kabl** [comment]
Right responding is a valid point. Have an option would be a nice feature. 
Even if it's responding or fixed ratio, no text or other elements should be moved out of the visible area.

**Comment by phryneas** [comment]
Is there currently any way to force such a behaviour, maybe even a fixed resolution? I am getting weird page overlap with some sizes and do not need any responsiveness, but a working presentation.

**Comment by glasser** [comment]
Yeah, if I know it's going to end up in a PDF it would be great to be able to preview it consistently at the target size.

**Comment by vlsi** [comment]
>but I think the default layout should be a responsive web-like layout

@jxnblk , can you please clarify? Does that mean you object adding fixed aspect ratios?

Conference equipment typically has 16x9 or other well-known format.

>I am getting weird page overlap with some sizes and do not need any responsiveness, but a working presentation

I fully agree. Having 16x9 presentation is way more important than having a responsive one.
I use "dev tools" very often as I develop slides, and I still want the slides to be 16x9 even though they don't occupy the whole screen.

So I guess the slides should be "

**Comment by jxnblk** [comment]
You *should* be able to do this with a custom theme and applying styles to the `Slide` component, see https://github.com/jxnblk/mdx-deck/blob/master/docs/theming.md#reference

**Comment by vlsi** [comment]
@jxnblk , hi there

I see #342 was merged, however, it seems to be absent in mdx-deck 4.1.1.

Was the future removed?
Are there challenges with aspect ratio?
