### ISSUE TITLE
Question: recommendation for showing component output and source code?

### ISSUE THREAD

**Issue by trevordmiller** [jxnblk/mdx-deck#126]
How would you recommend showing a component’s rendered output and it’s source code from the same source?

**Comment by trevordmiller** [comment]
Something like:

    import SomeComponent from "./components/SomeComponent"

    # Some Component

    <SomeComponent />

    ```jsx
    {some way to pull code from SomeComponent in here}
    ```

**Comment by jxnblk** [comment]
You might want something like https://github.com/FormidableLabs/react-live – which is what mdx-docs uses for live code previews

**Comment by trevordmiller** [comment]
Thanks for the info!

**Comment by trevordmiller** [comment]
For anyone else who stumbles on this, I recommend using code surfer: 
https://github.com/pomber/code-surfer

You can render output, then step through the source code like this:

```jsx
---

import SomeComponent from './components/SomeComponent'

<SomeComponent />

---

import CodeStepper from "./components/CodeStepper"

<CodeStepper
  code={require("!raw-loader!./components/SomeComponent")}
  steps={[
    { range: [1, 3], notes: "Some step 1" },
    { lines: [5, 10], notes: "Some step 2" },
    { range: [15, 20], notes: "Some step 3" },
    { lines: [22], notes: "Some step 4" }
  ]}
/>

---
```
