### ISSUE TITLE
Question: Using Slidedeck as a component, control deck externally

### ISSUE THREAD

**Issue by SirBryan** [jxnblk/mdx-deck#127]
I want to be able to “remotely” control the deck’s position, or even swap out the slides in a hot reload use case, so I’m trying to incorporate it as a child component.

When used under create-react-app, it appears that the mdx deck isn’t properly split into an array. After ejecting it, I was able to add the webpack customization, but webpack complains about “ignore” in the example. 

Changed the config to 
```
use: [ { loader: ‘babel-loader’, option: { ignore: /node_modules/ } }, 
{loader: ‘mdx-deck/loader’, option: { ignore: /node_modules/ } ]
```

Which satisfies all of webpack and node’s compilation, but then instead of slides, I get some kind of node-modules/webpack gibberish with the temporary location of the mdx file.

Is there a working ```App.js``` demo file that works under CRA, before or after ejection?

**Comment by jxnblk** [comment]
The built in SlideDeck component is an uncontrolled component. You might want to look at how it’s built to see if you can use a combination of the other components it’s built with to build a custom component for your needs

**Comment by jxnblk** [comment]
For webpack, do you have `exclude: /node_modules/` in your rule?

**Comment by SirBryan** [comment]
I opened the issue from my phone and tried to do as much from memory as possible. So it appears the errors I was getting was from different attempts to clean up the Webpack config.

Now that I'm back my desk, I've found that I left it complaining about ```superbox``` being unavailable. I took the ```Box``` component out of the slides and they work.

This Webpack config:
```
{ test: /\.mdx$/,
  use : [ { loader: 'babel-loader', options: { ignore: /node_modules/ } },
	  { loader: 'mdx-deck/loader', options: { ignore: /node_modules/ } } ]
},
```
And this:
```
{ test: /\.mdx$/,
  exclude: /node_modules/,
  use: [ 'babel-loader', 'mdx-deck/loader' ]
},
```
both produce the same results, i.e. it's working as a child component for vanilla slides.

However...

After including ```superbox``` and ```styled-components``` in the parent app/component, then using the same slide deck that I used with just  ```mdx-deck```, the slides don't split properly.

**Comment by jxnblk** [comment]
Are you using the mdx-deck loader?

**Comment by jxnblk** [comment]
Sounds like this **might** be an issue with multiple versions of styled-components installed. You can try a clean install with `rm -rf node_modules && npm i` to see if that helps – also checking to see if there are multiple versions by running `npm ls | grep styled-components`

Also #132 might be helpful

**Comment by SirBryan** [comment]
I’ll have to play with it.

In the meantime, using a custom Provider tied to Socket.io allowed me to prototype what I was originally trying to do.

Demo here (for reference): https://twitter.com/sirbryan/status/1033104720439590912?s=21

#132 looks good too.

**Comment by SirBryan** [comment]
I’m going to close this issue in favor of #132.

**Comment by chaychoong** [comment]
> I’ll have to play with it. In the meantime, using a custom Provider tied to Socket.io allowed me to prototype what I was originally trying to do. Demo here (for reference): https://twitter.com/sirbryan/status/1033104720439590912?s=21 #132 looks good too.

This looks awesome. Do you have a repository somewhere for that?

**Comment by SirBryan** [comment]
My fork of this repository (it says it's 7 months behind, but I'm sure you could pick out the parts you need):

https://github.com/SirBryan/mdx-deck

No guarantees about the current state; I left this project to tackle some others. I do need to get back to it though.
