### ISSUE TITLE
`styled-components` as peerDependency

### ISSUE THREAD

**Issue by IcanDivideBy0** [jxnblk/mdx-deck#128]
Shouldn't `styled-components` be a peerDependency ?

**Comment by jxnblk** [comment]
It’s a dependency for the CLI to work, so no. That said, there might be a case for making the components available as a standalone library

**Comment by IcanDivideBy0** [comment]
Maybe `mdx-deck` should hold the standalone library and `mdx-deck-cli` a separate module ?
Currently using `mdx-deck` as a library might create a ton of duplicate modules depending on the project it is used.

**Comment by jxnblk** [comment]
That’s sort of what I was suggesting, except the new package would be `mdx-deck-components`

**Comment by IcanDivideBy0** [comment]
Would be nice !
I can try to give it a shot if you create the repository ?

**Comment by IcanDivideBy0** [comment]
or i create it and you'll fork it later ?

**Comment by IcanDivideBy0** [comment]
or lerna ?

**Comment by jxnblk** [comment]
I'm thinking the package could be generated within this repo's `prepare` script – I can look into it over the weekend if you wanted to take a shot at it

**Comment by jxnblk** [comment]
Closing in favor of #132
