### ISSUE TITLE
Markdown tables do not properly render

### ISSUE THREAD

**Issue by jxnblk** [jxnblk/mdx-deck#13]
Due to https://github.com/jxnblk/mdx-deck/blob/master/lib/loader.js#L14

**Comment by busypeoples** [comment]
How would you approach solving this?

Adding pipes on the sides works obviously.

```
// will work

| One           | Two           |
| ------------- | ------------- |
| Cell          | Cell          |
| Cell          | Cell          |


// will not work

One           | Two
------------- | -------------
Cell          | Cell
Cell          | Cell


```

**Comment by jxnblk** [comment]
Tables should render now. You can customize how they look with custom components, but I'll open another issue for adding some default table styles
