### ISSUE TITLE
Consider adding separate `mdx-deck-components` package

### ISSUE THREAD

**Issue by jxnblk** [jxnblk/mdx-deck#132]
- For use in other React apps
- Should be generated from existing code base if possible
- *OR* be added as a dependency to the core package
- Does not include dependencies for CLI/webpack/etc

**Comment by iamstarkov** [comment]
this would be nice to use in next.js

**Comment by timofei7** [comment]
or within a larger gatsby setup organizing many decks, played around a little with trying to use the components but didn't get very far.  i think separating out as a dependency to the core package seems like a pretty standard way to go about it.

**Comment by iamstarkov** [comment]
@jxnblk I'm confused. Did you close this issue as in "won't fix" or as in "released"? =)
