### ISSUE TITLE
"Cannot read property 'index' of null" in mdx-deck 1.6.7 "Notes" on build

### ISSUE THREAD

**Issue by trevordmiller** [jxnblk/mdx-deck#138]
When using `Notes` like

```jsx
import { Notes } from 'mdx-deck'

<Notes>
  Only visible in presenter mode
</Notes>
```

When I run `mdx-deck build` I get `TypeError: Cannot read property 'index' of null` originating from `node_modules/mdx-deck/dist/Notes.js:44:24`:

![image](https://user-images.githubusercontent.com/5497885/44622983-e53c1380-a880-11e8-9350-9f7d516f061a.png)

in mdx-deck 1.6.7

**Comment by trevordmiller** [comment]
This works though:

    ```notes
    These notes are only visible in presenter mode
    ```

**Comment by jxnblk** [comment]
Thanks! I'm able to reproduce, I imagine it has something to do with `webpack-node-externals` not being set up correctly, but I'm looking into it
