### ISSUE TITLE
Question: how to bundle assets like images in build?

### ISSUE THREAD

**Issue by trevordmiller** [jxnblk/mdx-deck#139]
I added a `static/` directory to put offline assets in like images. Then I use them like:

```jsx
import { Image } from "mdx-deck"

<Image src="./static/thing.gif" />
```

This works with `mdx-deck` (dev mode), and `mdx-deck pdf`, but not `mdx-deck build`. Is there a good way to include offline static assets with builds?

**Comment by trevordmiller** [comment]
My current workaround is to copy my `static/` folder in npm scripts:

```
    "build": "npm run clean && npm run static && npm run html && npm run pdf",
    "clean": "rm -rf docs",
    "static": "mkdir -p docs/static && cp -R src/static docs/",
    "html": "mdx-deck build src/index.mdx -d docs",
    "pdf": "mdx-deck pdf src/index.mdx -d docs",
```

Then `npm run build` gives me everything I need to host the presentation.

**Comment by pomber** [comment]
I use it like this:
```jsx
<img src={require("file-loader!./somthing.png")}/>
```

**Comment by aleclarson** [comment]
Any plans to support `![](../static/foo.gif)`?

**Comment by ashrafhasson** [comment]
> I use it like this:
> 
> ```js-jsx
> <img src={require("file-loader!./somthing.png")}/>
> ```

I get a `Uncaught ReferenceError: require is not defined` using this technique to load images in dev mode.
