### ISSUE TITLE
allow auto export to PDF at a special URL

### ISSUE THREAD

**Issue by dharmeshkakadia** [jxnblk/mdx-deck#141]
This a request to add a feature that allows exporting to PDF automatically. 

Like for example I can enable a config and slides available at https://braziljs.now.sh/  can be exported to pdf to say https://braziljs.now.sh/export/pdf or something like that ?

This removes the borden on creating and hosting PDFs from authors and allows audiences to consume in whatever form they like. 

Based on https://twitter.com/dharmeshkakadia/status/1033775247533649920

**Comment by jxnblk** [comment]
Generally speaking you should be able to print to pdf, but this will not guarantee consistent styling. Exporting the PDF before deploying, with a link to download is the best way to go about this IMO

**Comment by dharmeshkakadia** [comment]
Thanks for the response. I think with a way to trigger pdf conversion by going to a special URL removes the burden from authors to not only host PDFs, but keeping it up to date. This is where mdx-deck workflow excels really well and keeping a separate copy has all the problem of traditional powerpoints/keynotes/PDFs etc. - you loose the ability for version control, cheap consistent styling, updateability and so on.

Feel free to close if you disagree however and thank you again for making mdx-deck!

**Comment by jxnblk** [comment]
> going to a special URL removes the burden from authors to not only host PDFs, but keeping it up to date

Right now mdx-deck exports a static site, so hosting any related static assets like a PDF could be done at the same time – it might make sense to add a `--pdf` flag (or similar) to the `build` command to make it easier to do it all at once. From a simplicity from the end-viewer perspective, I think downloading a file is much easier and more consistent than expecting them to print to PDF. This also gives authors more control over what formats are available

**Comment by dharmeshkakadia** [comment]
Thanks 👍
