### ISSUE TITLE
Explicit Google Fonts Array

### ISSUE THREAD

**Issue by kyleshevlin** [jxnblk/mdx-deck#148]
I have a talk that uses two Google fonts, but one of them is only used in `h1` and `h2` tags and I can't seem to get mdx-deck to add that other Google font as a `<link>`. It got me thinking that it might be worthwhile to add an explicit option for `googleFonts` to force their linkage.

Could be something like:

```
{
  ...theme,
  googleFonts: [
    { name: 'Open Sans', weights: [300] },
    { name: 'Bungee' }
  ]
}
```

I could work on a PR for this feature if you thought it would be worth having in the project.

**Comment by jxnblk** [comment]
You can use the Head component to add font links. I’ll likely deprecate the automatic loading in the next major version fwiw

**Comment by kyleshevlin** [comment]
Thanks. Hadn't thought of that as a solution. Appreciate it.
