### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by trevordmiller** [jxnblk/mdx-deck#152]
First, thanks so much for such an awesome library!

If possible, could release notes be added when a release is made?

Current:

![image](https://user-images.githubusercontent.com/5497885/44921331-8d2d6300-acff-11e8-9678-1a72565bf2c8.png)

Suggested example:

![image](https://user-images.githubusercontent.com/5497885/44925869-d89a3e00-ad0c-11e8-97e4-c8d6e25d1169.png)

**Comment by jxnblk** [comment]
Generally I use GitHub releases in my repos, but for this one I'm trying a [changelog](https://github.com/jxnblk/mdx-deck/blob/master/CHANGELOG.md)

**Comment by trevordmiller** [comment]
@jxnblk Oh cool! Sorry I totally missed that :) Thanks again for all you do!

**Comment by trevordmiller** [comment]
Not sure if it is hard to do but linking to the changelog from each release might be helpful. Like Prettier does:

https://github.com/prettier/prettier/releases

https://github.com/prettier/prettier/releases
