### ISSUE TITLE
Using Layouts with multiple mdx files with multiple slides per file

### ISSUE THREAD

**Issue by christopherjbaker** [jxnblk/mdx-deck#153]
When using a single mdx file loaded directly, I can add `export { Split as default } from 'mdx-deck/layouts'` to a single slide to split that one. When importing mdx files into a javascript file (such as when "combining multiple mdx files", I receive an error that I cannot have multiple default exports.

**Comment by jxnblk** [comment]
Instead of using the default export syntax, I'd recommend wrapping the slide with the component as outlined here: #326
