### ISSUE TITLE
Cannot use nested lists in Markdown

### ISSUE THREAD

**Issue by chasemccoy** [jxnblk/mdx-deck#154]
Just a small thing I noticed, it appears that nested lists in Markdown don't work correctly. 

The following:

```
- Item one
- Item two
  - Sub item one
  - Sub item two
- Item three
```

should render two `<ul>` elements, but instead just includes the text of the sub items inside the parent `<li>`.

**Comment by SaraVieira** [comment]
Hey !

Can you specify what is wrong in this markup?

<img width="1552" alt="screen shot 2018-09-03 at 21 28 21" src="https://user-images.githubusercontent.com/1051509/44999818-5174f080-afc0-11e8-9e12-8ca621392b54.png">

**Comment by chasemccoy** [comment]
@SaraVieira Nothing is wrong with that markup, that is what I would expect. However, that is not the markup being generated by the Markdown I posted above.

**Comment by SaraVieira** [comment]
That's weird, I pasted your code into my presentation and that's what I got :/

<img width="1136" alt="screen shot 2018-09-03 at 21 31 56" src="https://user-images.githubusercontent.com/1051509/44999887-cba57500-afc0-11e8-9b98-c79ee8f74655.png">

**Comment by chasemccoy** [comment]
How strange... what version of `mdx-deck` are you using?

**Comment by SaraVieira** [comment]
"mdx-deck": "1.7.1",

What version you in ?

**Comment by chasemccoy** [comment]
Same here. On second look, it seems as if pasting that in works for me, but earlier when I had typed it in manually it did not. I wonder if this is just Markdown being picky about spacing, etc. Gonna close this for now.

**Comment by SaraVieira** [comment]
Oh yeah, I get those small markdown bugs all the time too :/

**Comment by Amleth** [comment]
I have the same problem. 

> I wonder if this is just Markdown being picky about spacing, etc.

I don't think so, and the problem occurs regardless of the markdown context around the nested list.
