### ISSUE TITLE
puppeteer as peerdependency

### ISSUE THREAD

**Issue by timneutkens** [jxnblk/mdx-deck#157]
Not everyone might have the use case of exporting to pdf / creating a screenshot. In my case I'm on a 500Kbps connection at home and installing mdx-deck via simple `yarn add mdx-deck` takes so long that I had to switch to my phone 4G connection which is 40Mbps. Even then it takes 50seconds to install though. So the simplest solution to me seems like making puppeteer a peer-dependency 🙏

**Comment by jxnblk** [comment]
Yeah, been pondering this. I wonder if the PDF script should be a separate package altogether, rather than in the main CLI. Something like `mdx-deck-pdf`

**Comment by timneutkens** [comment]
Sounds like a great solution 👍:pray:

**Comment by millette** [comment]
I didn't want to mention it since I saw the pdf export was issue #3 (so, part of the original plan). Glad you're ok with it :-)

**Comment by simonhaenisch** [comment]
Another approach I know (from [StencilJS](https://github.com/ionic-team/stencil/blob/master/src/sys/node/node-lazy-require.ts)) is "lazy dependencies":

```js
// package.json
{
  "lazyDependencies": {
    "puppeteer": "^1.10.0"
  }
}
```

Then, only when the `pdf` sub-command is invoked, run a function that ensures that the packages required for that command are installed, and install them if missing.

**Comment by Siilwyn** [comment]
Another solution would be using `puppeteer-core` this is an easy switch, the only difference being it expects chrome to be installed.

**Comment by jxnblk** [comment]
Removed puppeteer from the core CLI in v2, so hopefully it'll be a smaller install size going forward – PDF/PNG export is now available with the separate `@mdx-deck/export` CLI package

**Comment by styfle** [comment]
|version | install size |
|-------:|--------------|
| 1.8.2 | [![install size](https://packagephobia.now.sh/badge?p=mdx-deck@1.8.2)](https://packagephobia.now.sh/result?p=mdx-deck@1.8.2) |
| 2.0.0-8 | [![install size](https://packagephobia.now.sh/badge?p=mdx-deck@2.0.0-8)](https://packagephobia.now.sh/result?p=mdx-deck@2.0.0-8) |

Looks good! 🎉
