### ISSUE TITLE
Quick start initializer error

### ISSUE THREAD

**Issue by danmarshall** [jxnblk/mdx-deck#164]
Hello, I'm really excited to try out this project. When trying to use the [Quick Start](https://github.com/jxnblk/mdx-deck#quick-start) method from the readme:
```
npm init deck foo
```
I get this error:
```
curl: (23) Failed writing body (0 != 6850)
[ERROR] failed to create mdx-deck
[ERROR] { Error: Command failed: curl https://codeload.github.com/jxnblk/mdx-deck/tar.gz/master | tar -xz -C foo --strip=3 mdx-deck-master/templates/basic
```

Also, an alternative "quick start" could be a link to an example repo that we could fork to start a new project.

**Comment by danmarshall** [comment]
Yes I’m on Windows

**Comment by jxnblk** [comment]
See c8r/initit#2

**Comment by danmarshall** [comment]
Thanks. In the meanwhile, could you create a HelloWorld sample repo? 🙏

**Comment by jxnblk** [comment]
`npm init deck` copies this directory FWIW https://github.com/jxnblk/mdx-deck/tree/master/templates/basic

**Comment by danmarshall** [comment]
Thanks!

**Comment by jxnblk** [comment]
Going to close this out. I'd recommend installing dependencies manually and creating new projects from scratch
