### ISSUE TITLE
Using with remote controller

### ISSUE THREAD

**Issue by Wraithraiser** [jxnblk/mdx-deck#165]
Hello, thanks for this awesome lib :)

I apologize if my question is irrelevant but I usually use a remote controller in my presentation and I can't get it to work with mdx-deck.

Do I have to stay near my laptop or is there a specific model of remote controller that work good with mdx-deck ?

**Comment by millette** [comment]
You might have to click once with the mouse on the content for the keyboard (controller) to take affect. If that doesn't work, can you tell us more about the remote?

**Comment by Wraithraiser** [comment]
For exemple, when I use a PowerPoint presentation, I use a DinoFire Wireless Presenter but it seems to be specific to PowerPoint presentation or similar type of presentation like Prezi. I can't configure the buttons.

mdx-deck switch with left/right and not up/down. I can't find a remote control to match mdx-deck

**Comment by Wraithraiser** [comment]
I found a solution, thanks for mentioning the mouse... I just have to buy a tiny wireless mouse with buttons and configure it. Don't know why I didn't think about it before haha

Thanks for the help :) I close the issue.
