### ISSUE TITLE
Modes

### ISSUE THREAD

**Issue by jxnblk** [jxnblk/mdx-deck#17]
It would be great to have separate modes for presenting, editing, etc. This is a placeholder for discussing what that could look like

**Comment by johno** [comment]
As far as presenting is concerned, I think it'd be cool to expose the presenting notes as some sort of component. That way we can hide the content unless we're in presentation mode. Though I'm not sure if we want the contents to be JSX or MD.

```jsx
# Hello, world!

<MDXDeck.Notes>
  Here are some notes for the presenter.

  Not sure if this should be <b>JSX</b> or _markdown_.
</MDXDeck.Notes>
```

**Comment by jxnblk** [comment]
I would probably lean more towards JSX within the component, maybe with an optional `md` prop if we wanted markdown – seems more inline with the MDX spec

**Comment by Eudecio** [comment]
This is an incredible library!

**Comment by jxnblk** [comment]
Closing in favor of more specific issues now that presenter mode is in – #41
