### ISSUE TITLE
Yarn usage fails

### ISSUE THREAD

**Issue by millette** [jxnblk/mdx-deck#170]
With the latest release, it appears installing and using with yarn fails:

```
[mdx-deck] rendering static html
Warning: Failed context type: Invalid context `__styled-components-stylesheet__` supplied to `Component`.
    in styled.div
    in div
    in Swipeable
    in Unknown
    in Provider
    in Unknown
    in MDXProvider
    in ThemeProvider
    in Unknown
    in HeadProvider
    in SlideDeck
    in App
    in StyleSheetManager
[mdx-deck] bundling js
```

* If I use npm instead it works.
* If I add styled-components as a dependency to my project, it works with yarn too.

I didn't investigate further yet.

**Comment by millette** [comment]
If I add styled-components v3.4.5 to my own package, I can yarn build.
If I add the latest, v3.4.9 I get the same error as above.

**Comment by millette** [comment]
I forked mdx-deck and used yarn link to figure out what is happening in my project. Used this way, mdx-deck installed the latest styled-components (v3.4.9) and I didn't need to add it to my own project.

In other words, the next release of mdx-deck should automatically fix this as long as the latest styled-components is picked up.

**Comment by jxnblk** [comment]
Is anything failing or are you just seeing the warning?

**Comment by millette** [comment]
It's not building after the warning.

**Comment by millette** [comment]
Removed my styled-components dep, upgraded mdx-deck to 1.7.7 and happy to report it now works. Thanks!

**Comment by luizcieslak** [comment]
@millette, I still have this error even with mdx-deck 1.7.7. This is my devDependencies: 
```
  "devDependencies": {
    "mdx-code": "^1.1.3",
    "mdx-deck": "^1.7.7",
    "mdx-deck-code-surfer": "^0.5.5",
    "mdx-deck-live-code": "^1.0.0",
    "raw-loader": "^1.0.0"
  }
```
occuring in both yarn and npm. Can you paste your package,json?
