### ISSUE TITLE
babel 7 support

### ISSUE THREAD

**Issue by iamstarkov** [jxnblk/mdx-deck#174]
this would be nice

**Comment by jxnblk** [comment]
Have you tried installing `babel-core@7.0.0-bridge.0` either locally or in a fork of mdx-deck?

**Comment by iamstarkov** [comment]
@jxnblk I haven't tried it so far, but I guess it will work.

**Comment by zcei** [comment]
I used `babel-upgrade` and adjusted things here and there according to their docs. Will make a PR later the day.
