### ISSUE TITLE
v2 Roadmap

### ISSUE THREAD

**Issue by jxnblk** [jxnblk/mdx-deck#177]
This is a placeholder for potential major changes in the next version

- Split PDF export into a separate, optional package #157 
- Refactor & simplify components codebase 
- Handle focus trapping #93 
- New UI for presenting and modes, including touchscreen UI #6
- Update layout styles, simplifying custom layout components

**Comment by jamischarles** [comment]
Would love the ability to easily combine layouts like:

```mdx
---
export Split,Invert` 

# Heading
---
```
or something similar

**Comment by signalwerk** [comment]
* Multiple themes per deck ((deck with two kind of slides))
* Video-Component ((make it pop 🦄))

**Comment by iamstarkov** [comment]
I have two points:
* it would be nice to utilise default `mdx/loader`
* extract mdx-deck as a standalone package for easier integration into other frameworks (CRA, next)

**Comment by zcei** [comment]
@QuentinRoy I built kinda something like this when playing around with "one slide per step" PDF export.

Currently looks like this, steps are derived from whether the a component constructor calls `setSteps` (current behavior, abstraction could be better)

```
// Simple Appear, internally using steps
<ul>
  <Appear>
    <li>One</li>
    <li>Two</li>
    <li>Three</li>
    <li>Four</li>
  </Appear>
</ul>

// Using the `AppearComponent` directly
<Steps>
  {({ step, setSteps }) => {
    return (
      <ul>
        <AppearComponent step={step} setSteps={setSteps}>
          <li>One</li>
          <li>Two</li>
          <li>Three</li>
          <li>Four</li>
        </AppearComponent>
      </ul>
    )
  }}
</Steps>

---
```
is this something wanted? (cc: @jxnblk) I could make a PR out of it easily, but would like to discuss some state management concept, which would be subject to "Refactor & simplify components codebase"

**Comment by QuentinRoy** [comment]
@zcei I am open to it. It would enable me to do what I need. Does `<Step>` also accept class components (and still give it `step` and `setSteps` as argument)? If not that means a sub component needs to be created if one want to have access to [`componentDidUpdate`](
https://reactjs.org/docs/react-component.html#componentdidupdate). It is OK, but I think it would be nicer if one does not need that.

Something that bothered me a bit however is having `setSteps` as an argument. That implies it can it be called by the subcomponent multiple time. From what I have seen in the code, it seems it implies significant change (maybe that is what your refactor is about). Also, it is a bit unclear what would happen if `setSteps` is called with a value lesser than the current `step`? Would mdx-deck switch to the next slide?
These are the reasons I thought a Higher Order Component would be easier. It seems it can be implemented in a few line of codes. Though I agree that it requires a bit more React mastery from users.

**Comment by zcei** [comment]
The problem I saw with the HOC is that is required `mdx` to understand any arbitrary JS. As far as I know it only looks at `import` & `export` statements plus the `<` JSX indicator. 
So one would always need to move that code out of the presentation into its own file.

The `componentDidUpdate` thing is something I have to look into, did not consider it for the PDF export.

Yes, my refactor is about `setSteps` (or better the metadata management in itself). It should accept multiple components having steps, basically adding up the individual step counts to a total amount. How that would exactly looks like: don't know yet.
In general it's about the question whether the user should explicitly define the number of steps or it should be derived from the components on that slide. Open for discussion 🙂

**Comment by QuentinRoy** [comment]
Ah! Good point. I didn't thought about that.

I believe `setSteps` can only be derived automatically in the case of adding elements (which I think is already pretty well done by `<Appear>`). But my use case requires more than that. What if elements shouldn't be added but replaced, and what if something else needs to be done using the step argument (e.g., again, updating a D3 chart).

**Comment by zcei** [comment]
> I believe setSteps can only be derived automatically in the case of adding elements

Yes, that's why I exposed it, as a lot of use-cases won't have this luxury.

> What if elements shouldn't be added but replaced, or what if something else needs to be done using the step argument 

I think then you need a component that in the contructor sets the steps and if necessary during the lifetime it would call `setSteps` again to update it current totals? 🤔 This way we would definitely need to store the steps per component in the state, so that it can later be updated. 

Would you know the exact steps up front for D3 stuff? And do you trigger the next step by yourself, or should D3 say that the next step starts by emitting some event? Just trying to get a solid understanding of different use-cases.

**Comment by QuentinRoy** [comment]
> Would you know the exact steps up front for D3 stuff?

Yes. In my case I would always know. Maybe there is cases where you do not but, I do not have any in mind..

> And do you trigger the next step by yourself, or should D3 say that the next step starts by emitting some event?

No in my use case I want to trigger the even myself. This being said, having and API to programmatically change step would be interesting as well. But I think that is something else.

**Comment by jxnblk** [comment]
Would you mind opening another issue related to a render prop based API for Appear? I want to make sure the thoughts related to that don't get lost

**Comment by QuentinRoy** [comment]
Done, see #193. I tried to briefly summarize the discussion.

**Comment by mrcasablr** [comment]
Would like the placement of content in Layout like it gitpitch snaplayouts - https://medium.com/@gitpitch/snap-layouts-for-gitpitch-markdown-presentations-29800f642586

As you already captured, layouts could use more love.

**Comment by jxnblk** [comment]
> The themes should probably never use pure black

For presenting on a projector, you generally *do* want "pure black" (and generally higher contrast) because of the nature of projectors

**Comment by jxnblk** [comment]
Just published v2 beta, which should resolve some of the things mentioned here. Feel free to open other new issues with any additional feature requests

**Comment by iamstarkov** [comment]
@jxnblk can you update either CHANGELOG.md or GitHub releases with more details about what has been released?
