### ISSUE TITLE
Possible bug: lists inside of lists

### ISSUE THREAD

**Issue by trevordmiller** [jxnblk/mdx-deck#181]
With markdown like this:

![image](https://user-images.githubusercontent.com/5497885/46044195-4dc41d80-c0d7-11e8-8194-60c516851d01.png)

I'm getting weird paragraph wrapped output from lists within lists:

![image](https://user-images.githubusercontent.com/5497885/46044168-3e44d480-c0d7-11e8-912c-94875fc2f6b3.png)

**Comment by jxnblk** [comment]
See https://github.com/mdx-js/mdx/issues/262
