### ISSUE TITLE
PDF export of slides using Split are empty

### ISSUE THREAD

**Issue by sylvhama** [jxnblk/mdx-deck#183]
I could reproduce with mdx-deck 1.7.1 and 1.7.7.

Create a `deck.mdx` file, copy paste this:
```
import { Split } from 'mdx-deck/layouts'

# LEFT

# RIGHT

export default Split
```

Then run `mdx-deck pdf deck.mdx`. The PDF will be empty however the web version looks fine.

**Comment by hxuanhung** [comment]
it seems similar to #121, I can have a look at it.

**Comment by orhaneee** [comment]
I can confirm that bug.

**Comment by jxnblk** [comment]
I think this should work now in v2. Feel free to reopen if you're still seeing issues
