### ISSUE TITLE
Slide styling

### ISSUE THREAD

**Issue by signalwerk** [jxnblk/mdx-deck#188]
Is there an option to style the [Slide](https://github.com/signalwerk/mdx-deck/blob/master/src/Slide.js#L7-L23) per theme?

**Comment by bjab** [comment]
I'm interested in this too, especially in setting background image for slide.

**Comment by jxnblk** [comment]
You can use per-slide layouts to change colors, add background images, etc. 
https://github.com/jxnblk/mdx-deck#layouts

**Comment by bjab** [comment]
Yes, I ended using per-slide Layout, but IMHO it's not convenient to add custom Layout to every slide just to set background image.
Problem is, that if you define background image on theme level (and set it to background-size:cover), then it's looking ok in HTML, but in PDF image is stretched across all slides. 
So style that will be defined globally in theme, but applied to every slide item, would be helpful.

Maybe it's just matter of exposing some class names for styling?

**Comment by jxnblk** [comment]
This might be something to consider for the next major version, but I don’t think exposing `classNames` as part of the public API is good idea

**Comment by signalwerk** [comment]
@jxnblk wouldn't it be an option just to pass in the style (via API) to the [root](https://github.com/signalwerk/mdx-deck/blob/master/src/Slide.js#L7-L23)  and if you don't the default styling kicks in. This would not break with existing users and people can still do what they want if they need to.

**Comment by mrcasablr** [comment]
@signalwerk  do you have an example of per slide styling using Layouts?

**Comment by signalwerk** [comment]
@mrcasablr In the doc you find the section [Layout](https://github.com/signalwerk/mdx-deck/blob/master/README.md#layouts)

**Comment by Taar** [comment]
You could define your own `Provider` [(docs)](https://github.com/jxnblk/mdx-deck/blob/master/docs/advanced.md#custom-provider-component) (assuming you're using the latest version).
```jsx
import React, { useEffect } from 'react'

export function BackgroundProvider ({ children }) {
  useEffect(function BGIEffect () {
    document.body.style.background = `url('assets/bg-image.jpg')`
    document.body.style.backgroundRepeat = 'no-repeat'
    document.body.style.backgroundPosition = 'center'
    document.body.style.backgroundSize = 'cover'
  })
  return <>
    { children }
  </>
}
```

Then inside `theme.js`:

```js
import { BackgroundProvider as Provider } from './components/BackgroundProvider'

export const customTheme = {
  font: 'Roboto, sans-serif',
  colors: {
    text: '#ffffff',
    background: 'transparent'
  },
  Provider
}
```

Note that for this to work, your provider must be set to the key [`Provider`](https://github.com/jxnblk/mdx-deck/blob/master/packages/components/src/Provider.js#L23) in your theme. You also need to get the background to `transparent` in your theme.

It might not be the best solution but it's worked well for me so far :confetti_ball:

**Comment by jxnblk** [comment]
The `Slide` component can now be styled in v2 themes, see https://github.com/jxnblk/mdx-deck/blob/master/docs/theming.md#reference

**Comment by karlhorky** [comment]
For those who cannot upgrade to v2 yet (such as users of `code-surfer`), here's an ugly temporary workaround / hack for styling `Slide`s with a provider (haven't tested this extensively yet):

`Provider.js`

```js
import React from 'react';

export default function Provider({ children }) {
  return (
    <>
      {/*
        Hack to give Slide components a relative
        position (for absolute positioning further
        down)
      */}
      <style
        dangerouslySetInnerHTML={{
          __html: `
            [class^="Slide__Root-"] {
              // Your styles here
            }
          `,
        }}
      />
      {children}
    </>
  );
}
```

`theme.js`

```js
import { default as theme } from 'mdx-deck/themes';
import Provider from './Provider';

export default {
  ...theme,
  Provider,
};
```
