### ISSUE TITLE
Slide changes during development

### ISSUE THREAD

**Issue by JuanCaicedo** [jxnblk/mdx-deck#196]
Hi there! I'm sorry if this isn't the right place for this, feel free to let me know and I'll close it and ask in a better location 😄

I'm currently trying to develop a presentation and I'm finding that if I 
- Make a few slides
- Navigate to slide #3 http://127.0.0.1:8080/?mode=overview#3
- Make a change to slide 3
- Wait for hot reload to happen

Then the slide gets properly updated (🎉), but the slide deck navigates to slide #0 (though the url does not update).

Does this seem like a bug? It does seem like it would be useful to be able to keep the slide locked. For example, this would be useful for testing out a few different CodeSurfer themes, or if you are making live edits during a presentation (😱)

**Comment by jxnblk** [comment]
Yeah, this sounds like a bug. If you can share a reproduction of the issue, that'd be helpful

**Comment by JuanCaicedo** [comment]
I'd be glad to! Unfortunately, I'm not sure what I'm doing differently today, but the problem seems to have gone away 😅 Let me wait a couple days to see if it happens again and I can get more info, otherwise I'll close this issue 👍

**Comment by jxnblk** [comment]
@JuanCaicedo please let me know if this is still an issue

**Comment by JuanCaicedo** [comment]
Sorry about that 😅
