### ISSUE TITLE
using react-live with mdx-deck

### ISSUE THREAD

**Issue by jole78** [jxnblk/mdx-deck#203]
Hey,

first of all thanks for a great project!
I'm trying to add some live coding experience into a deck. Saw that the recommended way was to use react-live.
However when I add that and try add react-live to my deck I get an error:
```
Uncaught TypeError: Cannot read property 'tokTypes' of undefined 
at Module.eval (buble-browser.es.js:269)
    at eval (buble-browser.es.js:10378)
    at Module../node_modules/buble/dist/buble-browser.es.js (main.js:970)
    at __webpack_require__ (main.js:725)
    at fn (main.js:102)
    at eval (react-live.es.js:26)
    at Module../node_modules/react-live/dist/react-live.es.js (main.js:3218)
    at __webpack_require__ (main.js:725)
    at fn (main.js:102)
    at eval (index.js:16)
```

// in index.mdx
```
import {
  LiveProvider,
  LiveEditor,
  LiveError,
  LivePreview
} from 'react-live'

---
<LiveProvider code="<strong>Hello World!</strong>">
  <LiveEditor />
  <LiveError />
  <LivePreview />
</LiveProvider>

```
mdx-deck version 1.7.7

any ideas??

**Comment by jxnblk** [comment]
Haven't had time to dig in, but I've seen that same error in other places. I suspect a change somewhere in the dependency tree is causing that

**Comment by johno** [comment]
The [current (albeit temporary) fix](https://github.com/c8r/x0/issues/106#issuecomment-431586436) is to pin `buble` to `0.19.4`. The current version of `buble` is what's causing this error and hasn't been fixed upstream yet.

**Comment by jole78** [comment]
@johno thanks, that fixes it even though it might be temp right!?

**Comment by jole78** [comment]
@johno thanks, that fixes it even though it might be temp right!?

**Comment by jole78** [comment]
@johno thanks, that fixes it even though it might be temp right!?

**Comment by jole78** [comment]
@johno thanks, that fixes it even though it might be temp right!?

**Comment by jole78** [comment]
@johno thanks, that fixes it even though it might be temp right!?

**Comment by jole78** [comment]
@johno thanks, that fixes it even though it might be temp right!?
