### ISSUE TITLE
SideDeck component on create-react-app failed styles

### ISSUE THREAD

**Issue by raichuk** [jxnblk/mdx-deck#205]
Hi Brent, first of all thanks for the fantastic work.

I succesfully extracted the SideDeck component in order to use it with `create-react-app` (specifically with `react-app-rewired` for merge new webpack config ) using this `config-overrides.js` to add the `mdx-deck/loader`:

```
const { getBabelLoader } = require('react-app-rewired')

module.exports = (config, env) => {
  const babelLoader = getBabelLoader(config.module.rules)
  config.module.rules.map(rule => {
    if (typeof rule.test !== 'undefined' || typeof rule.oneOf === 'undefined') {
      return rule 
    }
    
    rule.oneOf.unshift({
      test: /\.mdx?$/,
      use: [
        {
          loader: babelLoader.loader,
          options: babelLoader.options
        },
        'mdx-deck/loader'
      ]
    })

    return rule
  })

  return config
}
```

And implemented simply with this:

```
import React, { Component } from 'react';

import { SlideDeck } from 'mdx-deck'
import slides from './deck.mdx'
import { comic } from 'mdx-deck/themes'

class App extends Component {
  render() {
    return (
      <SlideDeck
        slides={slides}
        theme={comic}
      />  
    );    
  }     
}
      
export default App;
```

The only problem I found is that styles aren't being correcly applied, the theme is ok but the position of titles is strange and when I resize window it's not responsive as using directly from `mdx-deck`.. I assume that something of `styled-components` is not set correctly but I am not sure.

Thanks in advance.

**Comment by dziamid** [comment]
Want to embed <SlideDeck /> in my app as well. Sounds like the library assumes that it takes over the whole viewport - there are many viewport specific sizes (100vh, 100vw) throughout components that, once turned off, renders the slides correctly.

**Comment by jxnblk** [comment]
The internals have changed a bit since v1. I'm planning on having better support for using MDXDeck components in other libraries in v3, but closing this out for now, since `create-react-app` isn't really something this library is intended to work with
