### ISSUE TITLE
'background' key compiles to 'background-color'

### ISSUE THREAD

**Issue by motleydev** [jxnblk/mdx-deck#207]
Is there a way to provide a custom background image? I'm trying to use radial gradients but it's not supported by the `background-color` property. As a user, I kind of expected "background" to compile to the matching css shorthand value instead of `background-color`.

**Comment by jxnblk** [comment]
Sorry, not sure I understand the question. Can you provide a code example of what you’re talking about?

**Comment by jxnblk** [comment]
The theme `colors` object does have a `background` value, but I feel like `colors.background` is fairly explicit, unless I’m missing/forgetting about something

**Comment by motleydev** [comment]
I suppose `colors.background` is one way to look at it. For me I feel like this is what my mind tends to gravitate towards:

`background => background`
`backgroundColor => background-color`
`backgroundImage => background-image`

Specifically because `background` in css can take the full spectrum of variants from gradients, to colors, to images. I get the idea that colors.background is probably explicit enough, it still tripped me up for a while. I just wonder if there's a more explicit way to explain that?

**Comment by jxnblk** [comment]
Right but the theme takes a `colors` object, not a general background value
