### ISSUE TITLE
PDF export of slides with code-surfer doesn't seem to be supported

### ISSUE THREAD

**Issue by ledicjp** [jxnblk/mdx-deck#211]
Is it only me or is the export to PDF not supported for slides that use the code-surfer library?

**Comment by jxnblk** [comment]
Possible duplicate of #183

**Comment by jxnblk** [comment]
With the changes in v2, Code Surfer will need to have a default view of showing whatever makes sense when `steps === Infinity` - closing this here, but feel free to continue the discussion on the Code Surfer repo
