### ISSUE TITLE
Prettier adds suport for MDX

### ISSUE THREAD

**Issue by afontcu** [jxnblk/mdx-deck#215]
Hi! 👋 Prettier [just announced](https://prettier.io/blog/2018/11/07/1.15.0.html) that version `1.15` adds support for MDX files.

Would that be a nice addition for mdx-deck? If that's the case, I'd happily submit a PR with the version bump and the necessary configuration for `.mdx` files.

Thanks for your work!

**Comment by jxnblk** [comment]
Are you suggesting setting up prettier for development of this repo? If so, I’d accept a PR with updates for this

**Comment by afontcu** [comment]
Hi! Yes. I think it makes sense now that mdx files can be _prettified_ too. I'll work on that and come back to you with a PR :) 

Thanks!

**Comment by jxnblk** [comment]
I think the repo has prettier set up now, please open another issue if its not working correctly
