### ISSUE TITLE
Allow hashes in production build

### ISSUE THREAD

**Issue by kapral18** [jxnblk/mdx-deck#216]
# Reason for the change:

I hosted the slides on gh-pages and first thing I noticed was that `npm run build` always produces `index.html` and `main.js`. 

And github caches the files for some time. 

The obvious workaround is cache busting with webpack output hashes.

```javascript
//webpack.config.js
module.exports = {
  output: {
    filename: "[name].[chunkhash:8].js"
  }
};
```

But in your `build.js`:

```js
  log('bundling js')
  const config = createConfig(opts)  // first merge 

  config.mode = 'production'
  config.output = { // then completely overwrite the provided output
    path: opts.outDir
  }

  const compiler = webpack(config)
```

Is there a reason behind it?

# Suggested solution:

The most non-invasive one could be:

```javascript
  log('bundling js')
  const config = createConfig(opts);

  config.mode = 'production'
  config.output.path = opts.outDir;

  const compiler = webpack(config)
```

What do you think?

**Comment by jxnblk** [comment]
My initial thinking was that CLI flags should always override configuration from files. I suspect you could change the `—out-dir` flag to add the hash, but in this case, it might make sense for the webpack config to take precedence

**Comment by kapral18** [comment]
Correct me if I am wrong. 

```js
config.output = {
    path: opts.outDir
}
```

here you just overwrite whatever you merged from your cli pointed custom `webpack.config.js`. And also `path` can only contain the actual path to output, you cannot point to hashed files there, so I am not sure what do you mean by 

> you could change the —out-dir flag to add the hash

Could you clarify that and could you comment on suggested solution on whether it's ok as a temp solution to allow hashing? Or otherwise could you show how to achieve the same differently?
