### ISSUE TITLE
PDF exports Payara page

### ISSUE THREAD

**Issue by aloifolia** [jxnblk/mdx-deck#218]
For me, the PDF exports seems to be not working, at all. The generated presentation.pdf looks like the following screenshot. How does this happen?

I am using mdx-deck 1.7.7.

<img width="682" alt="screen shot 2018-11-09 at 12 39 32" src="https://user-images.githubusercontent.com/1295054/48260663-8b2d0200-e41c-11e8-93e5-d321379868b8.png">

**Comment by jxnblk** [comment]
It looks like you have another local server running. To export to PDF, mdx-deck starts in dev mode then uses Puppeteer to render the PDF. Can you check to see if the dev mode works on its own with your setup?

**Comment by aloifolia** [comment]
That was it. By using a different port, the pdf export worked.
