### ISSUE TITLE
Can't seem to get the fonts to work

### ISSUE THREAD

**Issue by JJ** [jxnblk/mdx-deck#220]
I'm trying to get this test deck to work:
```
import { Head } from 'mdx-deck'

<Head>
  <title>Git! Push</title>
  <meta name='twitter:site' content='@jjmerelo' />
  <meta name='twitter:title' content='Git! Push! What is it good for?' />
  <meta name='twitter:description' content='Absolutely everything!' />
  <link href="https://fonts.googleapis.com/css?family=Allerta+Stencil|Open+Sans" rel="stylesheet" /> 
</Head>


export { default as theme } from './theme'

# Git! Push!
## What is it good for!
# Absolutely everything!
---
# That's me!

---
<code>git push!</code>
```

With this theme.js
```
// example theme.js
import { future } from 'mdx-deck/themes'
import okaidia from 'react-syntax-highlighter/styles/prism/okaidia'
import prismBash from 'react-syntax-highlighter/languages/prism/bash'
const monospace = 'SFMono-Regular, Consolas, Liberation Mono, Menlo, Courier, monospace'
const allerta = 'Allerta Stencil, sans-serif'
const opensans = 'Open Sans, sans-serif'

export default {
	...future,
    font: allerta, opensans,
    heading: {
	fontFamily: allerta,
    },
    h1: {
	fontSize: '5em',
	textTransform: 'none',
	fontFamily: allerta,
    },
    h2: {
	fontSize: '3em',
	textTransform: 'none',
	fontFamily: opensans,
    },
    prism: {
	style: okaidia,
	fontSize: '2em',
	languages: {
	    bash: prismBash
	}
    }
    
}

```
(heavily inspired by [@broccolini's deck](https://github.com/broccolini/design-systems-and-react)). However, the fonts are not set correctly; they seem to use the default font. Any help? Also, are there any other examples? It would help if they were linked directly from the README.md

**Comment by jxnblk** [comment]
This `const allerta = 'Allerta Stencil, sans-serif'` needs to be correct CSS syntax. I’d check with Google Fonts to find the right value for this font

**Comment by JJ** [comment]
I'm changing to another font, Koho, but still it does not seems to work.

**Comment by JJ** [comment]
I'm checking several fonts and apparently the problem is that it can use
correctly some "common" fonts such as Lato or Roboto, but does not include
other fonts like Koho or Allerta and the mechanism that includes that in
the header is not apparently working.

**Comment by jxnblk** [comment]
This has changed since v2. I'd recommend using the `<Head>` component to add stylesheet links for custom webfonts
