### ISSUE TITLE
Stacking boxes vertically in a new component (and advice on component path)

### ISSUE THREAD

**Issue by JJ** [jxnblk/mdx-deck#222]
I'm trying to create a new component that splits the slide vertically. Here's what I came without any error:

```js
import React from 'react'
import styled from 'styled-components'
import Flex from './node_modules/mdx-deck/dist/Flex'
import Box from './node_modules/mdx-deck/dist/Box'

const Root = styled.div([], {
  width: '100vw',
  height: '100vh',
})

const SplitHorizontal = ({ children }) => {
  const [a, ...rest] = React.Children.toArray(children.props.children)

  return (
    <Root>
      <Flex
        css={{
         flexDirection: 'row',
          alignItems: 'center',
          height: '100%'
        }}>
        <Box height={1 / 2}>
          {a}
        </Box>
        <Box height={1 / 2}>
          {rest}
        </Box>
      </Flex>
    </Root>
  )
}

export default SplitHorizontal
```
(which is ripped from Split, actually). It kind of works, but basically does not stack anything vertically, but works pretty much in the same way as Split or SplitRight. I have tried to look up if Box needs some additional styling, but can't seem to find anything.
Other that that, please check that I'm using the actual filesystem path to Flex and Box. Don't know if I should use any other. I have tried others with the mdx-deck prefix, to no avail.

**Comment by sehgalvibhor** [comment]
If you want to align them vertically, you should change to  `flex-direction: 'column'`. It will align them vertically as per your need.

**Comment by JJ** [comment]
Not really. There's no apparent difference between that and `row` or, for that matter, not using this component at all.

**Comment by sehgalvibhor** [comment]
Try this: 
https://github.com/sehgalvibhor/mdx-deck-layouts/blob/master/VerticalFlex.js

I used this to create a vertical stack of items.

**Comment by JJ** [comment]
That looks fine. Thanks!
