### ISSUE TITLE
Appear without List Items

### ISSUE THREAD

**Issue by sehgalvibhor** [jxnblk/mdx-deck#223]
I am trying to use `<Appear/>` transition without the List elements. Is it possible?
I know I can do this with ordered/un-ordered list. 

For example: I have two header elements which I want to appear sequentially, h1 and then h2 based on the keypress event. How should I achieve this?

**Comment by sehgalvibhor** [comment]
Got it :)

**Comment by jxnblk** [comment]
Yes, any direct child elements should work with Appear
