### ISSUE TITLE
Access current layout instance in Provider

### ISSUE THREAD

**Issue by codepunkt** [jxnblk/mdx-deck#227]
Is there a way to access the current layout instance in `Provider`?

I've replaced the dots with a bar in a custom provider and use Layouts that apply darkened/brightened `cover` background-images to slides and adapt the headline and text colors to match the background-image.

I'd love to also adjust the progress bar colors in provider based on the colors used in the current layout, but found no way to access it from Provider.

**Comment by jxnblk** [comment]
Not that I know of, but would need to be something that's supported in the core MDX package if it is somehow available – you might try looking at the source for how MDX handles layouts
