### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by aputinski** [jxnblk/mdx-deck#228]
Following the instructions in the README, I can't get this simple example to start:

https://github.com/aputinski/mdx-deck-test

```
ERROR in ./node_modules/mdx-deck/dist/entry.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3".
```

**Comment by jonsherrard** [comment]
I've been using mdx-deck for a while, I just installed on a new machine and I'm getting this error as well. Will investigate and check back shortly.

**Comment by vpicone** [comment]
Also experiencing this, can't create any new projects or run sample. Might have something to do with babel-plugin-styled-components > @babel/plugin-syntax-jsx?

**Comment by jxnblk** [comment]
Related https://github.com/styled-components/babel-plugin-styled-components/issues/182
