### ISSUE TITLE
Support for .jsx extension

### ISSUE THREAD

**Issue by jollytoad** [jxnblk/mdx-deck#231]
I've just attempted to add my first component into an mdx-deck presentation, and hit this issue which stumped me for a while... I was getting:

`Module not found: Error: Can't resolve './components/Foo' in '...'`

after much head scratching, and searching, i realised my component ended in .jsx - as usual, but mdx-deck doesn't support this. Renaming to .js works - but breaks my editor.

Any chance support for .jsx could be added?

Thanks
- Mark

**Comment by jxnblk** [comment]
This should be supported now, so closing this out
