### ISSUE TITLE
Appear.js assumes Window exists

### ISSUE THREAD

**Issue by programbo** [jxnblk/mdx-deck#233]
https://github.com/jxnblk/mdx-deck/pull/186 was merged in five days ago and breaks the build script because of `window.navigator.userAgent.includes('Print/PDF')` at https://github.com/programbo/mdx-deck/blob/cc142d16edf42098e0dc54764c63e93e106c6232/src/Appear.js#L32

Would suggest making sure `window` exists before using it.

**Comment by jxnblk** [comment]
Published as `1.8.2`
