### ISSUE TITLE
PDF export does not display emojis.

### ISSUE THREAD

**Issue by aloifolia** [jxnblk/mdx-deck#235]
If I include emojis like 😊, they are not displayed in the generated PDF file. This happens if I just add it as text but also if the emoji is nested in an Appear-block or inside an SVG file.

**Comment by jxnblk** [comment]
Sorry for the delay! I'm not really sure what was happening (might have been an issue with Puppeteer), but emoji seem to work in PDF export in v2 so closing this out for now
