### ISSUE TITLE
How do I use the Head component when using multiple mdx files?

### ISSUE THREAD

**Issue by NotMyself** [jxnblk/mdx-deck#236]
I have a deck where I have [multiple mdx](https://github.com/jxnblk/mdx-deck/blob/master/docs/advanced.md#combining-multiple-mdx-files) files using a deck.js that looks like this:

```javascript
export { default as theme } from './theme'

import title from './slides/title.mdx'
import about from './slides/about.mdx'
import code from './slides/code.mdx'
import end from './slides/end.mdx'

export default [
  ...title,
  ...about,
  ...code,
  ...end
]
```

I would like to use the [Head](https://github.com/jxnblk/mdx-deck/blob/master/docs/components.md#head) component to inject a none commonjs compliant script.

```javascript
import React, { Component } from 'react'
import { Head } from 'mdx-deck'

class DeckHead extends Component {
  render() {
    return (
      <Head>
        <script src='https://unpkg.com/snapsvg@0.5.1/dist/snap.svg-min.js'></script>
      </Head>
    );
  }
}

export default DeckHead;
```

How do I reference this component in my deck.js?

**Comment by jxnblk** [comment]
You should be able to render the `<Head />` component in any of the MDX files (I'd suggest at the top of the first one), but let me know if that doesn't work for some reason

**Comment by NotMyself** [comment]
@jxnblk thanks, this doesn't work for my specific use case. The react components in the deck fail to render because they have a dependency on the script that I am adding via the <head /> tag. It would be nice if I could export it from the deck.js file like I can the theme.

**Comment by jxnblk** [comment]
Ah, I think I see what you're trying to do, but you'll probably need to roll your own component that appends a script tag to the head on mount. The mdx-deck Head component is only really intended for things like title, meta tags, etc.

**Comment by NotMyself** [comment]
@jxnblk gotcha, thanks for the response.
