### ISSUE TITLE
How to change font size of code?

### ISSUE THREAD

**Issue by mplis** [jxnblk/mdx-deck#238]
Something like this in my `theme.js` doesn't seem to work (neither does `pre`). I noticed that `code` and `pre` aren't in the reference of the theme docs, either.

```js
export default {
    ...baseTheme,
    code: {
        fontSize: '10px'
    }
};
```

Is there any way to decrease the font size of code blocks, either for the whole presentation or on a specific slide?

**Comment by mplis** [comment]
I was using syntax highlighting and I think that was the problem.

In case you still want to see them, here are snippets from the relevant files:

```
# deck.mdx
export { default as theme } from './theme';
...

# theme.js
import { dark as baseTheme } from 'mdx-deck/themes';
import prismStyle from 'react-syntax-highlighter/styles/prism/tomorrow';
import prismJson from 'react-syntax-highlighter/languages/prism/json';
import prismGraphql from 'react-syntax-highlighter/languages/prism/graphql';
import prismHttp from 'react-syntax-highlighter/languages/prism/http';

export default {
    ...baseTheme,
    prism: {
        style: prismStyle,
        languages: {
            json: prismJson,
            graphql: prismGraphql,
            http: prismHttp
        }
    },
    // code: { fontSize: '12px' } <- this wasn't working
    // pre: { fontSize: '12px' } <- and neither was this
};

```

**Comment by jxnblk** [comment]
With the changes in v2, the theme should target *any* `<pre>` or `<code>` tag, not just those created in MDX, which should resolve this issue. If you'd like to give it a shot, the beta can be installed with `npm i mdx-deck@next`
