### ISSUE TITLE
Theming not working

### ISSUE THREAD

**Issue by GAumala** [jxnblk/mdx-deck#242]
Hi, I think mdx-deck is pretty cool and decided to make my first presentation with it this weekend but I'm having a little bit of trouble.

I need some block quotes and lists, but the default styling doesn't seem right to me so I decided to create my own theme that uses italic font for block quotes and centers list items. For some reason it is not working.

I'm running the latest version 1.8.2. Here's my code.

### index.mdx
``` mdx
export { default as theme } from './Theme.js'

# This is the title of my deck
---

> some qoute

- one
- two
- three
---
# The End
```

### Theme.js

``` javascript
// example theme
import theme from 'mdx-deck/themes'

export default {
  ...theme,
  blockquote: {
    fontStyle: 'italic'
  },
  li: {
    textAlign: 'left'
  }
}
```

### package.json

``` json
{
  "name": "mdx-sample",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@mdx-js/tag": "^0.16.6",
    "react": "^16.7.0"
  }
}
```

## Actual Result

The browser shows the same default theme. the quote text is not in italics and the list items align to center instead of left.

![screenshot from 2019-01-06 20-19-12](https://user-images.githubusercontent.com/5729175/50744447-468dcf00-11f1-11e9-9937-7cb8133fbeef.png)

## Expected Result

If I edit styles with the browser's dev tools I can get the expected result

![screenshot from 2019-01-06 20-26-09](https://user-images.githubusercontent.com/5729175/50744483-7ccb4e80-11f1-11e9-9afb-b0ad4b3b487d.png)

**Comment by tgallacher** [comment]
hey @GAumala, might be a typo but your `package.json` doesn't appear to have the `mdx-deck` dependency?

Could you also post the command used to run the example above, e.g. `mdx-deck index.mdx`, etc.

**Comment by GAumala** [comment]
Hello!

I installed `mdx-deck` globally with yarn so I run the example with `mdx-deck index.mdx`.

**Comment by jxnblk** [comment]
Sorry for the delay, this *might* be an issue with the global install. Can you verify whether the issue still occurs with a local install?

**Comment by GAumala** [comment]
That actually worked. 

installed `mdx-deck` as a dev dependency with Yarn and then ran `node_modules/.bin/mdx-deck index.mdx `. Everything styles correctly, also bold text in headers is a lot bigger. 

Thanks for the help!

**Comment by jxnblk** [comment]
Sounds good – I suspect it might be an issue with styled-components, which can not work as expected when there are multiple/conflicting versions
