### ISSUE TITLE
"Open in Normal mode" link

### ISSUE THREAD

**Issue by dcastro** [jxnblk/mdx-deck#243]
When in presenter mode, the "Open in Normal mode" button assumes the slides are hosted at the root `/`. When the slides are hosted under a different path, e.g. `https://mysite.com/myslides/`, then the button's link will wrongly point to `https://mysite.com/#0`.

I'm on version 1.8.2.

PS: This is my first time using `mdx-deck`, so far I'm loving it, thanks for all your efforts!

**Comment by jxnblk** [comment]
This *should* work as expected in v2, but please feel free to reopen if you're still seeing issues
