### ISSUE TITLE
Import ".md" files

### ISSUE THREAD

**Issue by artalar** [jxnblk/mdx-deck#244]
Hi!
Can you add the possibility to import `md` and `mdx` files?

Currently it possible (how i found) only after that's steps:

- Install dependencies: `mdx-loader babel-core babel-loader@7 babel-preset-react babel-preset-stage-2`
- Add `.babelrc` at project root and fill it by `{ "presets": ["react", "stage-2"] }`
- Import needed files like this: `import MDText from '!babel-loader!mdx-loader!./my-file.md'`

**Comment by jxnblk** [comment]
Unfortunately, mdx-deck uses a custom loader to convert mdx files into an array of components. Your solution above is currently the best way to use a different loader for mdx files with the CLI
