### ISSUE TITLE
yarn pnp

### ISSUE THREAD

**Issue by jimthedev** [jxnblk/mdx-deck#247]
Hey there. Great tool. Thanks for building it. I was trying to speed up the initial install and thought I might try using yarn's pnp. It doesn't seem to work but I was hoping to be able to make it happen since it could speed up the 'time to first slide'. Have you used yarn pnp before or would you consider PRs to make it work?

**Comment by jxnblk** [comment]
Sorry for the delay and thanks! I haven't tried Yarn PNP before, but if it's easy to support that, I'd accept a PR. With v1 the install can be particularly slow because of the Puppeteer dependency, which is going away in v2, FWIW

**Comment by jxnblk** [comment]
Closing for now, will still accept a PR if that's something you're interested in
