### ISSUE TITLE
Transclude other decks in index.mdx

### ISSUE THREAD

**Issue by liuderchi** [jxnblk/mdx-deck#248]
> ### tl;dr; Transcluding other `*.mdx` in `index.mdx` is not very convenient

### Use case

Let's say we want to __insert a preface deck `preface.mdx` to original decks__

something like this:

```mdx
// index.mdx
import Preface from './preface.mdx'  // ADDED

# Title

MDX-based presention decks
---

<Preface />

---
```

### Observation

By following [mdx official doc about transclusion](https://mdxjs.com/syntax#markdown-file-transclusion), found that
- The __default export__ of `*.mdx` files is __NOT__ a renderable component; it's a plain JS array containing component
- to re-use `preface.mdx` in `index.mdx`, we need a js module to wrap it like this

```js
// preface.mdx.wrapper.js
import React from 'react'
import Mdx from './preface.mdx'

const Component = Mdx[0]

export default () => <Component />
```

changes in index.mdx:

```mdx
// index.mdx
import Preface from './preface.mdx.wrapper'  // CHANGED

# Title

MDX-based presention decks
---

<Preface />

---
```

### Summary

Hopefully transcluding mdx files (see https://mdxjs.com/syntax#exports) can be easier for mdx-deck users

**Comment by jxnblk** [comment]
The mdx-deck/loader behaves differently than the official mdx loader, see https://github.com/jxnblk/mdx-deck/blob/master/docs/advanced.md#combining-multiple-mdx-files

**Comment by liuderchi** [comment]
@jxnblk thanks for this doc and I missed it.
