### ISSUE TITLE
Support for building multiple presentations or custom export filenames

### ISSUE THREAD

**Issue by chrisjpatty** [jxnblk/mdx-deck#260]
First of all, thanks so much for all the hard work that's gone into this package. It's been a HUGE timesaver building presentations for my job.

I have a scenario that I'm wondering if there's an easier way to support. I have built several presentations which all share the same theme, images, fonts, etc. And as such I've kept them all in the same repo so they can share assets. The problem comes at build time. As far as I can tell the default build script is only capable of outputing a single presentation at a time, and always names them as `index.html` and `main.js`. This is a fine for building a single presentation, but what I've had to do is write my own wrapper around the `mdx-deck` build script which catches the files after they've been output and renames them. Would it be possible to add a configuration option that allows the user to specify the output filenames in the CLI? I'm envisioning something like this:

```bash
mdx-deck build presentation.mdx --filename custom-name
```

Which would output the following:

```
├── dist/
│   ├── custom-name.html
│   ├── custom-name.js
```

Or alternatively, the build script could accept an array of presentation arguments, which it would use to automatically generate these filenames like this:

```bash
mdx-deck build slides1.mdx slides2.mdx slides3.mdx
```

Which would output:

```
├── dist/
│   ├── slides1.html
│   ├── slides1.js
│   ├── slides2.html
│   ├── slides2.js
│   ├── slides3.html
│   ├── slides3.js
```

If I was more comfortable with Webpack I would just put in a pull request myself, but as it stands I thought I would just bring this use-case to your attention. I've solved this problem for myself with some ancillary tooling, but it would be nice to have it baked in for future projects.

One other thought, at first run, I anticipated that the build script would also copy any static assets being used and include them in the dist folder. Would this as an option also be possible? I've ended up having to write a post-build script that finds the assets and copies them to the build folder so all of the relative links still work. Anyways, just a thought.

Thanks again!

**Comment by jxnblk** [comment]
Open to exploring this further, but generally for CLI APIs, I prefer keeping them fairly simple. Could your issue be resolved by using the `-d` flag to output to different directories? E.g. `mdx-deck build one.mdx -d dist/one && mdx-deck build two.mdx -d dist/two` Guessing it might make sharing static assets a little trickier, but curious if this could work for your situation

**Comment by chrisjpatty** [comment]
Yeah the problem came when I tried to share assets between multiple output directories. I even tried to add a custom webpack config with a "public" folder path defined in the define plugin, but I couldn't get the mdx files to inherit the value from that key. If that were possible the output directory flag would work great since I could lift the assets up a level for production only.

The main issue at hand seems to be asset management. If there were a better way to output a shared static asset folder it would resolve this use-case. I totally get wanting to keep the CLI simple 😉. Maybe it could be driven by a config file that's documented in the advanced docs and isn't required. 

One other thought I had is that maybe the `-d` option could accept a full filename path. So `mdx-deck slides.mdx -d dist/customname.html` would also be a valid argument, and would trigger the output to be renamed, but this would be optional. That way we wouldn't need an additional CLI flag.

**Comment by karlhorky** [comment]
One further use case for building multiple slideshow decks would be to enable quick switching between them during a longer course.

For example, if I have 5 different presentations that I would like to present over the course of a day (but not deploy online), it would be nice to be able to switch between them in an easy way. To achieve this, I could imagine the following workflow:

1. building all presentations ...and...
2. building a list page linking to all presentations (like [this list](https://relay-modern-course.now.sh/packages/) from [this repo](https://github.com/sibelius/relay-modern-course))

**Comment by sibelius** [comment]
Here is a example of multiple mdx-deck https://github.com/sibelius/relay-modern-course

in a monorepo

it was deployed using now.sh here: https://relay-modern-course.now.sh/packages/

it would be cool to run all slides all at once for development and be able to link one set of slides in another one

**Comment by jxnblk** [comment]
The new [Gatsby theme](https://github.com/jxnblk/mdx-deck/tree/master/packages/gatsby-theme) lets you develop multiple decks at once in the same site. This will be the recommended way going forward, so closing this issue for now
