### ISSUE TITLE
Proposal: Docs Site

### ISSUE THREAD

**Issue by chrisjpatty** [jxnblk/mdx-deck#262]
Hi, I just wanted to propose the idea of creating a dedicated documentation site for `mdx-deck`. I have been really impressed with this project, and would like to contribute. I know how demanding open-source projects can be, so if you'd be interested I would be happy to undertake creating the documentation site. The goal would be to leverage the current markdown docs to auto-generate a static site that could be hosted on Github Pages or Netlify, and then hook that build process into your current deployment workflow.

**Comment by jxnblk** [comment]
Thanks for the suggestion! For now, I'd like to keep the docs hosted on GitHub, but with changes I'm considering later, this might make sense. I *would* be open to a better setup with Netlify or Now deploys for the demo deck though
