### ISSUE TITLE
Pass additional config to react-syntax-highlighter (e.g. showLineNumbers)

### ISSUE THREAD

**Issue by codesections** [jxnblk/mdx-deck#264]
Currently, the user can set the syntax highlighting theme and the supported languages in their theme.  However, they cannot pass any of the [many other props that react-syntax-highlighter accepts](react-syntax-highlighter).  Several of these seem like they might be too complex to usefully pass in from a theme, but a few look like they'd be useful.  

In particular `showLineNumbers`, `startingLineNumber`, `lineNumberContainerStyle`, and `wrapLines` all seem like they would be useful.  Would it make sense to pass them in?

If so, I'd be happy to submit a PR to add that functionality.

I've already modified the relevant code in `mdx/src/Code.js` for my local copy (I really wanted line numbers!) so it wouldn't be much effort to summit a PR if you think the feature would be more broadly useful.

**Comment by jxnblk** [comment]
With the changes in v2, you can now supply your own syntax highlighting component with a theme, which should let you specify any props you'd like for react-syntax-highlighter and also install newer versions of the library. Here's an example of what adding syntax highlighting to a theme now looks like: https://github.com/jxnblk/mdx-deck/blob/master/packages/themes/src/syntax-highlighter.js
