### ISSUE TITLE
Theming styles working inconsistently between markdown / html / components

### ISSUE THREAD

**Issue by amberleyromo** [jxnblk/mdx-deck#265]
Hi there!

Wondering what I could be doing wrong here. Following the docs to include the `<Appear>` component, for list items.

When using a markdown unordered list, the theming styles apply as expected:

```
- Item one
- Item two
- Item three
```

<img width="1202" alt="screen shot 2019-02-27 at 11 13 21 am" src="https://user-images.githubusercontent.com/3461087/53509160-dda03600-3a80-11e9-82dc-16a53513ae04.png">

When converting it to use `<Appear>`, the styles don't take effect:

```
<ul>
  <Appear>
    <li>Item one</li>
    <li>Item two</li>
    <li>Item three</li>
  </Appear>
</ul>
```

<img width="1269" alt="screen shot 2019-02-27 at 11 14 21 am" src="https://user-images.githubusercontent.com/3461087/53509168-e133bd00-3a80-11e9-9992-be3323886b98.png">

**Comment by jxnblk** [comment]
You're not doing anything wrong at all! 😬 Although the current implementation isn't ideal, the theming *only* applies to MDX components at the moment, which means only elements generated from markdown will pick up those styles. And with the way MDX itself works, you can't nest markdown inside of a React component like `Appear`.

With the current version, the best way I know of styling both markdown lists and JSX elements the same way would be to add a global style for `<ul>`. I think adding a custom `Provider` would be the way to go, where you could add a styled-component that targets child `<ul>`

Maybe something like:

```js
const Root = styled.div({
  '& ul': {
    ...listStyles
  }
})
```

**Comment by jxnblk** [comment]
This will still be an issue, but just merged v2, which should resolve this issue. You can install the beta with `npm i mdx-deck@next` if you want to give it a shot
