### ISSUE TITLE
Author Name in Slides

### ISSUE THREAD

**Issue by Athul-CA** [jxnblk/mdx-deck#266]
Hey,
This is Awesome Work.
I am trying to create a presentation but I want to add **my name in every Slides**  linking to Github account.   
I tried **layouts** but it only works in the **_First Slide_**. I've also tried **components** but I couldn't figure a way out. Plus I'm a total Noob.
Here I'm adding my Component's code .

```JSX
//name.js
import React from 'react'

export default({children})=>(
  
  <divstyle={{ 
      position: `absolute`,
      bottom:`10px`,
      left:`18px`,
      fontFamily:`Ubuntu`,
      fontSize:`20px` }}>
    <a href=" " >@Athul-CA</a>
      {children}
  </div>
)
```
and here is the code i've used in my deck 
```MDX
import name from './name'

# Workshop
---

export default name
```
It would be great if you could check into this. Thanks :confetti_ball:

**Comment by Athul-CA** [comment]
It would aslo be great if it was released as a Layout too.... :sweat_smile:

**Comment by jxnblk** [comment]
You’ll probably want a custom Provider component to wrap every slide https://github.com/jxnblk/mdx-deck/blob/master/docs/advanced.md#custom-provider-component

**Comment by Athul-CA** [comment]
Thanks it worked. 
I'll try add it as a component
