### ISSUE TITLE
Font don't seem to work in grid mode

### ISSUE THREAD

**Issue by glasser** [jxnblk/mdx-deck#267]
Grid mode (option-g) doesn't appear to support custom fonts?

```
$ git clone https://github.com/glasser/mdx-deck-grid-font-bug
$ cd mdx-deck-grid-font-bug
$ npm install
$ npm start
```

(The only change to the default `npm init deck` is setting theme.font to Lobster.

Normal view:
![image](https://user-images.githubusercontent.com/16724/53760038-9a760680-3e76-11e9-8c77-ae0d92ebab9c.png)

Option-g for grid view:
![image](https://user-images.githubusercontent.com/16724/53760058-a5309b80-3e76-11e9-8b77-207561066e34.png)

**Comment by jxnblk** [comment]
Sorry for the delayed response! I *think* this should no longer be an issue with v2. I'll do a quick test on the repro you provided

**Comment by jxnblk** [comment]
After looking into this I think #329 should fix this. Please feel free to reopen if you're still seeing the issue
