### ISSUE TITLE
Default Provider is not exposed

### ISSUE THREAD

**Issue by stam** [jxnblk/mdx-deck#271]
A lot of flexibility is gained by writing your own Provider component.
You cannot however make your own Provider render the mdx-deck provider as it is not exposed.

In my usecase I use the customprovider for custom styling.

**Comment by pengx17** [comment]
you could add re-provide the context to wrap your slides like this:

```
export const SlidesContext = createContext(undefined);
export function CustomProvider(context) {
  return <SlidesContext.Provider value={context}>{context.children}</SlidesContext.Provider>
}
```

**Comment by jxnblk** [comment]
The default provider just wraps the content with a fragment (https://github.com/jxnblk/mdx-deck/blob/master/packages/components/src/Provider.js#L10) - could you please clarify what you're intending to do?

**Comment by stam** [comment]
At the time of writing (1.10.0), the Provider which rendered the content together with the Progress indicator and previous & next buttons was not being exported.

I see that in v2, it is being exported, so this issue can be closed.
