### ISSUE TITLE
Can't import css files in build

### ISSUE THREAD

**Issue by HoverBaum** [jxnblk/mdx-deck#279]
Using version 2.0.0

While the dev server is working perfectly fine, as soon as I try to build my deck which has components that use an external stylesheet the build fails. the output I get is:

```
rm -rf dist && mdx-deck build index.mdx

[mdx-deck] building

✔ [mdx-deck]
  Compiled successfully in 3.73s

 DONE  Compiled successfully in 3730ms                                                                                                   

webpack:///./node_modules/style-loader/lib/addStyles.js?:23
        return window && document && document.all && !window.atob;
        ^

ReferenceError: window is not defined
```

While it does produce a `dist` folder, the contents of it does not work to display the presentation.

Digging into this I found #178 and noticed that the webpack config used by mdx-deck actually does include a style loader. And again, it works perfectly fine for the dev server, just breaks for building.

At a loss as to why this wouldn't work for builds.

**Comment by jxnblk** [comment]
Should be fixed in `2.0.4`, but if you still run into issues feel free to reopen this
