### ISSUE TITLE
Appear example produces wrong styles

### ISSUE THREAD

**Issue by vlsi** [jxnblk/mdx-deck#281]
# Versions

```json
{
  "private": true,
  "name": "my-code",
  "version": "1.0.0",
  "scripts": {
    "start": "mdx-deck deck.mdx",
    "build": "mdx-deck build deck.mdx",
    "help": "mdx-deck"
  },
  "devDependencies": {
    "mdx-deck": "^1.10.2",
    "mdx-deck-code-surfer": "^0.5.5",
    "raw-loader": "^0.5.1"
  },
  "dependencies": {
    "styled-components": "^4.1.3"
  }
}
```

# Issue
https://github.com/jxnblk/mdx-deck/blob/424dd9fdea50dac08d1f10a7a98bcb59a2d1b441/docs/components.md#appear

```jsx
import { Appear } from 'mdx-deck'
<ul>
  <li>One</li>
  <Appear>
    <li>Two</li>
    <li>Three</li>
  </Appear>
</ul>
```

It results in generic `ul/li` which have no styles.

Is there a simple way to use Appear+list?

# Workaround
So far I could get proper styling with the following approach:

```jsx
import { Appear, components } from 'mdx-deck'
const Li = components.li
const Ul = components.ul

<Ul>
  <Li>One</Li>
  <Appear>
    <Li>Two</Li>
    <Li>Three</Li>
  </Appear>
</Ul>
```

Is it "the simplest" way to make "animated one-by-one list"? Should the documentation be updated then?

**Comment by jxnblk** [comment]
Are you using MDX Deck v2? And do you have any additional MDX dependencies?

**Comment by vlsi** [comment]
@jxnblk , I'm using mdx-deck-code-surfer which doesn't seem to be compatible with MDX Deck v2, so I downgarded to 1.10.2.

**Comment by jxnblk** [comment]
In v1, the theming doesn’t apply to html elements, only markdown elements, so you’ll have to add styling for those on you own. V2 changes this behavior

**Comment by vlsi** [comment]
Ok, thanks.
