### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by jxnblk** [jxnblk/mdx-deck#29]
- [x] React component
- [x] Markdown code fences 
- [x] Should be themeable
- [x] Include JSX language by default
- [x] Add docs

**Comment by tomByrer** [comment]
[conorhastings/react-syntax-highlighter](https://github.com/conorhastings/react-syntax-highlighter) : Uses Lowlight, powerful, good docs, but requires a bit of configuration to have small file footprint

[akiran/react-highlight](https://github.com/akiran/react-highlight) : uses highlight.js, & also requires extra work to not include every language & skin.  Seems more lightweight, but docs are sparse

[Vamche/react-syntax-highlight](https://github.com/vamche/react-syntax-highlight) : also uses highlight.js, decent documentation, but unknown to React community so not many issues/PR/versions.

**Comment by jxnblk** [comment]
That first one looks great, thanks!

To clarify the theming bullet point, I'd imagine that the syntax theme could be added to an mdx-deck theme:

```js
// example theme
import { docco } from 'react-syntax-highlighter/styles/hljs'

export default {
  highlight: docco
}
```

Then automatically added to the syntax highlight component (and fenced code blocks) using the `withTheme` HOC

**Comment by busypeoples** [comment]
Is there anything missing here or can we close this issue?
