### ISSUE TITLE
Allow page index to be one later part of pathname

### ISSUE THREAD

**Issue by wgao19** [jxnblk/mdx-deck#291]
I'm building a speaker site and hoping to let it host my slides as well as a home page. The slides will have urls like this: http://my.site.cc/slides/yyyy-mm--topic-of-my-talk/. This works with my other slides built with reveal.js. But it does not work with mdx-deck. 

When I serve the deck directly, it works just as expected. But when I serve my site's root directory, it does not render any content although the JS is in place and the root is rendered with a few dummy nodes. Then when I slide with keyboard, the URL becomes .../NAN.

I looked around a little bit and find out that [here](https://github.com/jxnblk/mdx-deck/blob/master/packages/components/src/MDXDeck.js#L106) it fixes to reading only the index 1 of pathname, which is possibly causing the problem in routing.

I'm wondering, would it be OK for here to use, say, the last part or the last number of pathname?

**Comment by pengx17** [comment]
I also found this issue. I believe this issue may caused by a fact that mdx deck does not handle basepath other than `/`. A common fix is to use `<base>` attribute in html head and feed it to the underlying router component of reach router.

**Comment by wgao19** [comment]
Thank you for the tip! Will close this :]

**Comment by pengx17** [comment]
There is a possible solution I post in my fork here:
https://github.com/pengx17/mdx-deck/tree/feat/publich-path 

and demo:
http://pengx17.github.io/mdx-deck

Note that you may need a custom 404 page to make sure github pages works like a real SPA.
e.g.:

```html
<base href="/pages/pengxiao/slides/">

Redirecting ...

<script>
  location.href = '.';
</script>

```

**Comment by HoverBaum** [comment]
A better documented solution for this would be awesome. Lowering the hurdle to host mdx-decks on GitHub pages would be great.

**Comment by jxnblk** [comment]
Yeah, I think this is worth supporting, so reopening the issue

**Comment by jxnblk** [comment]
It's currently undocumented, but the CLI should now support a `--basepath` flag if anyone wants to check and see if that helps resolve this issue. The `basepath` is passed along to Reach Router, and you should be able to use it like `mdx-deck build deck.mdx --basepath="/slides"` – this is currently used internally in the `@mdx-deck/gatsby-theme` package, so I think it should work for this use-case as well

**Comment by 454de6e** [comment]
This does not work in v4.1.1. All `href` props in `index.html` contain root paths.

**Comment by karlhorky** [comment]
As mentioned over in https://github.com/jxnblk/mdx-deck/issues/535#issuecomment-855403988, here's a possible alternative:

Workaround: Using [`patch-package`](https://www.npmjs.com/package/patch-package), you can edit the internal Gatsby config and start command in `mdx-deck` to use the plugin [`gatsby-plugin-relative-paths`](https://github.com/MiguelSavignano/gatsby-plugin-relative-paths).

After you've installed `patch-package`, just add the following to a file at `patches/mdx-deck+4.1.1.patch` and run `npm install --force` or `yarn --force`:

```diff
diff --git a/node_modules/mdx-deck/cli.js b/node_modules/mdx-deck/cli.js
index 2c3be60..e263b3e 100755
--- a/node_modules/mdx-deck/cli.js
+++ b/node_modules/mdx-deck/cli.js
@@ -76,7 +76,7 @@ const gatsby = async (...args) => {
 
 switch (cmd) {
   case 'build':
-    gatsby('build').then(() => {
+    gatsby('build', '--prefix-paths').then(() => {
       const public = path.join(__dirname, 'public')
       const dist = path.join(process.cwd(), 'public')
       if (public === dist) return
diff --git a/node_modules/mdx-deck/gatsby-config.js b/node_modules/mdx-deck/gatsby-config.js
index 60247e3..3bae469 100644
--- a/node_modules/mdx-deck/gatsby-config.js
+++ b/node_modules/mdx-deck/gatsby-config.js
@@ -4,7 +4,9 @@ const src = process.env.__SRC__
 const dirname = path.dirname(src)
 
 module.exports = {
+  assetPrefix: '__GATSBY_RELATIVE_PATH__',
   plugins: [
+    'gatsby-plugin-relative-paths',
     {
       resolve: '@mdx-deck/gatsby-plugin',
       options: {
```

This seems to have some problems with images, but it is the solution that works the most out of a bunch that I've tried. Oh Gatsby :(
