### ISSUE TITLE
Custom provider use is misleading in the docs

### ISSUE THREAD

**Issue by vlsi** [jxnblk/mdx-deck#292]
https://github.com/jxnblk/mdx-deck/blob/master/docs/advanced.md#custom-provider-component

```js
export default {
  font: 'Georgia, serif',
  Provider,
}
```

It is not a valid JSON, and it is somewhat hard to understand what theming engine is looking for.

It looks like `export const themes=[{Provider: slideNumbers}]` works for `mdx-deck` 2 (`slideNumbers` is a function similar to https://github.com/jxnblk/mdx-deck/issues/180#issuecomment-460546242 )

**Comment by jxnblk** [comment]
The `Provider` is a React component, which is stated in the text accompanying the example. Do you have any suggestions on how to make that more clear?

**Comment by vlsi** [comment]
Well I tried again, and it works now. No idea what is was. Sorry for the noise.
