### ISSUE TITLE
Grid doesn't pass correct props to Slide component

### ISSUE THREAD

**Issue by Taar** [jxnblk/mdx-deck#297]
`Slide` uses the props passed as the object for its `Context.Provider`. When the program navigates to grid mode, the `Grid` component does not supply additional props. Therefore, `props` is `undefined` which means any component that uses the context will always get `undefined`. 

In the case of `Appear` it seems to work fine because `i < step` will return `false` if `step` is `undefined`.

I think the best way to fix this would be to define default prop values for `Slide` or perhaps using `Proptypes` to warn if the correct props aren't passed in. In that case, `Grid` would need to be updated to pass in the correct props with default values.

Let me know what you think. I could probably have a PR for this in the next day or so if you'd like :smile:

I would also like to update the Advanced docs with some examples on how to use `useSteps` and `Steps`.

**Update:**

`Overview` and `Presenter` also don't pass any props to `Slide` so they'll need to be updated as well.

If anyone runs into this, `step` is `undefined` when using `useSteps`, you can get around this by doing something like below which defaults to the first step:

```js
export default function MyStepper () {
  const step = useSteps(5)
  const currentStep = step != null ? step : 0 // 0 being the first step
  // ...
}
```

**Comment by jxnblk** [comment]
The Slide component now has a default prop set for `step`, along with some other refactoring. Feel free to open a new issue if you have any suggestions for how to make the new setup better
