### ISSUE TITLE
PDF export

### ISSUE THREAD

**Issue by jxnblk** [jxnblk/mdx-deck#3]
- [ ] Print styles
- [ ] CLI integration with Puppeteer

**Comment by Oluwasetemi** [comment]
Hey @jxnblk I don't know if I can help here!! I will like to contribute. I played with mdx-deck and i love it.
[my demo](https://dist-mzmkwjuacy.now.sh)

**Comment by jxnblk** [comment]
Thanks! Would love some help. For the print styles, I suspect they'll be tied to some other CSS changes that I'm planning to make, but the Puppeteer stuff could be hooked up separately. The readme has an example with PDF export: https://github.com/GoogleChrome/puppeteer 

I'd imagine this being a separate module in lib that could be consumed in `cli.js`
