### ISSUE TITLE
Build fails when using syntax-highlighter-prism

### ISSUE THREAD

**Issue by Kampfheizung** [jxnblk/mdx-deck#303]
Hey guys,

currently we're trying to finish our 2.0 migration but at the finish line we encountered 2 build errors that hinders us to use the new fancy major version.

1 error inside `./node_modules/mdx-deck/node_modules/@mdx-deck/themes/src/syntax-highlighter-prism.js`
```js
Module parse failed: Unexpected token (11:9)
You may need an appropriate loader to handle this file type.
| export const createCode = (opts = {}) => props => {
|   const language = getLanguage(props.className)
>   return <Prism {...opts} language={language} {...props} />
| }
| 
```

and 1 error inside `./node_modules/mdx-deck/node_modules/@mdx-deck/themes/src/syntax-highlighter.js`

```js
Module parse failed: Unexpected token (17:9)
You may need an appropriate loader to handle this file type.
| export const code = props => {
|   const language = getLanguage(props.className)
>   return <SyntaxHighlighter language={language} {...props} />
| }
|
```

our theme.js is looking like that:

```js
import theme, {syntaxHighlighterPrism} from '@mdx-deck/themes'
import okaidia from 'react-syntax-highlighter/dist/esm/styles/prism/okaidia'

export default syntaxHighlighterPrism({
  ...theme,

  css: {
    ...theme.css,
    backgroundImage: 'url(../images/background.svg)',
    backgroundPosition: 'top right',
    backgroundRepeat: 'no-repeat'
  },

  colors: {
    ...theme.colors,
    text: 'rgb(61, 77, 101)'
  },

  prism: {
    style: okaidia
  }
});

```

Do you guys have any suggestion how to proceed on that? Or what the problem really is?

Best regards,
the @farbenmeer team

**Comment by jxnblk** [comment]
Sorry for the delay! This looks like a babel issue. If you can point to a reproduction of this issue that'd be super helpful. Also could be helpful to see the full list of dependencies in a gist

**Comment by jxnblk** [comment]
Feel free to reopen if you can provide a reproduction
