### ISSUE TITLE
Switch slides on PageUp/Down keys

### ISSUE THREAD

**Issue by vlsi** [jxnblk/mdx-deck#310]
PageUp/Down is commonly used by clickers/presenters, so it makes sense to support that by default.

**Comment by unitehenry** [comment]
For these clickers, does the page up advance the slide or go back?

**Comment by vlsi** [comment]
For left-to-right languages pagedown is to advance the slides.
I've no idea what's the expected operation for right-to-left or top-to-bottom languages.

**Comment by vlsi** [comment]
Thanks for mdx-deck, it looks like the project is not suitable for presentations on stage: https://github.com/jxnblk/mdx-deck/pull/293
