### ISSUE TITLE
Contributing to this project

### ISSUE THREAD

**Issue by unitehenry** [jxnblk/mdx-deck#317]
Hi everyone.

I'm new to the open-source community, but I was trying to understand this project and wanted to contribute. I was trying to follow the contributing steps to develop for this project

# Development
1. Clone the repo
2. Install dependencies with npm install
3. Build with npm run prepare
4. Run npm start to see the demo docs/index.mdx

Not sure if this is just not updated or I'm missing something, but these steps aren't working for me. I'm essentially trying to understand how to build and test changes made to a clone/fork of this project. (I hope I'm using the right lingo too)

Anyways, thanks for you help!

**Comment by jxnblk** [comment]
Hi! Would love to have you contribute. Unfortunately, it does look like the contributing doc is outdated. I'll push an update, but in the meantime you can try running `yard && yarn start` – the repo is now set up as a monorepo with Yarn workspaces

**Comment by unitehenry** [comment]
Thanks that worked!

For anyone seeing this issue: ```yarn && yarn start```

**Comment by jxnblk** [comment]
I've updated the contributing doc to reflect this but please open a new issue if anything else is unclear
