### ISSUE TITLE
Add option to exclude notes when building deck

### ISSUE THREAD

**Issue by cowchimp** [jxnblk/mdx-deck#321]
Hi.

The ability to add `<Notes>` to the deck is great for when I'm presenting a deck from my laptop. Would be great though to exclude the notes from the exported deck when running `mdx-deck build` (assuming output file is meant to be shared online).

Would be happy to submit a PR if you agree and can give me some pointers on the best way to go about it.

Thanks.

**Comment by jxnblk** [comment]
Thanks! This is an interesting idea... Do other presentation libraries like Google Slides do this?

**Comment by cowchimp** [comment]
I couldn't find a feature like this in Google Slides but I think this is a valuable feature to have.

IMO if a an ability like this was available people would use it.

Right now I do this in a hacky way with a `prebuild` npm script that uses regex :scream: to remove the `<Notes>` from my deck.

**Comment by jxnblk** [comment]
Would an output flag that disables the presenter and other modes make sense for this? I’m guessing you want to share just the slides and not use this build for actually presenting?

**Comment by cowchimp** [comment]
Yes, the scenario here is to share the slides online for later reference, not to use them for presenting, so it would make sense to disable the presenter mode.
But the main point for me is that the actual Notes text won't be anywhere in the files that end up posted online, not just that they aren't shown on the screen. So it would mean not just disabling presenter mode but actively removing the Notes from the bundle.

**Comment by jxnblk** [comment]
I think your best best for something like this is a custom remark plugin to remove certain nodes. I think this is probably outside of the scope of this library, but if you'd like to submit a PR for a new remark plugin package, I'd be open to looking at it
