### ISSUE TITLE
mdx-deck should support custom master slide for layout

### ISSUE THREAD

**Issue by NateRadebaugh** [jxnblk/mdx-deck#332]
Similar to what is available for PowerPoint etc via "slide masters", it'd be cool to provide a "master layout" that can be used on all the slides.

Eg I'd like to swap out my existing presentations I use at my company with mdx-deck without getting weird looks or missing expected branding (logos/watermarks).

Fonts/content placement should be out of scope for this feature.

**Comment by jxnblk** [comment]
Does the custom Provider component not handle what you're describing? https://github.com/jxnblk/mdx-deck/blob/master/docs/advanced.md#custom-provider-component

**Comment by NateRadebaugh** [comment]
Thanks for the reply @jxnblk; I hadn't realized that existed.

Are there any additional docs/example for this? It looks like the only way to add a master image/watermark is via an an absolutely positioned item?

**Comment by jxnblk** [comment]
Currently it’s not documented more than this. It’s just a component that wraps the content of a deck so the API is essentially the same as any react component, so absolute positioning is certainly an option

**Comment by NateRadebaugh** [comment]
K thanks, I'll go from this!
