### ISSUE TITLE
Progress Dots Question

### ISSUE THREAD

**Issue by josefaidt** [jxnblk/mdx-deck#350]
I'm having an issue getting the progress dots to render in version v2.3.2, if I downgrade to v1.10 the dots will render. The only error I'm getting in the console is related to runtime, which oddly enough I get on my own Gatsby site. Not sure if that is what is causing the issue or if the dots were removed in recent versions.

**Comment by josefaidt** [comment]
I figured this one out after toying with the Provider, and seeing it exposes `slides` in an Array to create our own.

Closing

**Comment by jxnblk** [comment]
You've probably figured it out already, but the default Provider was removed in v2, see https://github.com/jxnblk/mdx-deck/blob/master/CHANGELOG.md#v200-2019-03-16

**Comment by josefaidt** [comment]
Yes I had to do a bit of digging, but I got there. Were the dots split off into a usable component?

**Comment by jxnblk** [comment]
Not yet but the plan was to make a couple default Provider themes, one of which would be a replacement for the v1 dots
