### ISSUE TITLE
Simulate presenter input in other window

### ISSUE THREAD

**Issue by aleclarson** [jxnblk/mdx-deck#363]
When I have two windows open (one in presenter mode), I want the input events from the presenter to be duplicated in the presentation window.

**Comment by jxnblk** [comment]
This would require syncing all browser events across tabs and not likely something this library would ever do

**Comment by aleclarson** [comment]
I only want to simulate mouse/keyboard events.

This would help: https://github.com/blakeembrey/simulate-event

All that's left is capturing those events in the presenter, send them to any connected windows via `postMessage`, convert the event coordinates, and then emit the event.

Deciding which element will receive the event could be tricky, unless targeting `document.body` handles hit detection and propagation for us (which it probably doesn't?).

**Comment by rbalicki2** [comment]
Is there a good workaround? Do you just need to click in the regular (presentation) window?

This is annoying because I would like to have a separate script on the laptop I'm looking at, and moving the mouse back and forth is not ideal
