### ISSUE TITLE
Use export const for props

### ISSUE THREAD

**Issue by iam-merlin** [jxnblk/mdx-deck#364]
Hi,

There is a way to pass props directly from the mdx to the slide (from what I saw... it's not possible).

What I'm looking for :

```jsx

export default SlideCustom
export const title = "My Title"

```

And I can see in SlideCustom props the value of title.

Right know, I'm doing something really, really, really, [...], really dirty (I take the first h1 in my presentation, dirty clone props to remove the first children and add title const) :

```jsx
import React from 'react'

import Content from '../../components/Content';
import Title from '../../components/Title';
import Wrapper from '../../components/Wrapper';

import Slide from "./Slide";

const extractProps = (props) => {
  if(props.children[0].props.mdxType === 'h1') {
    const cloneProps = { ...props };

    cloneProps.title = props.children[0].props.children;
    cloneProps.children = props.children.slice(1);

    return cloneProps;
  }

  return props;
};

export default (props) => {
  props = extractProps(props);

  return (
    <Wrapper>
      <Slide>
        <Title>{props.title || "Speakers"}</Title>
        <Content {...props} />
      </Slide>
    </Wrapper>
  )
}
```

**Comment by jxnblk** [comment]
Sorry for the delay! I'm not entirely sure what you're trying to do here, but if you're using slide layouts, you might want to look into this approach for passing props into the layout component: #326

**Comment by iam-merlin** [comment]
Hi, thx for the answer. I'm not trying because it works... but it's about passing props to a layout without using parametized components.

e.g. if I have `export MySlide = (props) => <Title>${props.title}</Title>` it would be nice to fill props using `export const title = "someTitle"`.

For example, in a mdx file 

```
import MySlide from "somewhere";

export default MySlide;
export const title = "someTitle";
```

instead of 

```
import MySlide from "somewhere";

<MySlide title="someTitle" />
```

It's just for "simplicity".

Nevermind, if `export default` is deprecated or will... Basic react usage is perfect ;)

**Comment by jxnblk** [comment]
Yeah, the `export default` syntax for layouts is definitely going away, so I'd suggest avoiding that if possible – generally speaking, in MDX you can export values to be used elsewhere, and there might be some custom APIs that MDX Deck adds on top of that (like `export const theme`), but otherwise it doesn't do anything too magical. Hope that helps, and it sounds like the original issue was addressed, so closing this out for now
