### ISSUE TITLE
Allow to set Presenter component via theme

### ISSUE THREAD

**Issue by codepunkt** [jxnblk/mdx-deck#365]
I'm currently working on my own presenter that emphasizes my Notes compared the current and next slides. I've found an easy way to change the Presenter component via theme - which basically requires to merge the themes in `MDXDeck` component instead of the Provider and then, based on the theme, either render the theme-provided Presenter or the default one. The merged could then also be passed to the `Provider` in order to not merge it twice.

It's not a lot of code changes and i'd love to contribute them to not have to maintain my fork. What do you think?

**Comment by codepunkt** [comment]
This would also easily allow things like #46.

Here is a short clip of the presenter that i've built for my presentations - just to give you an idea:
![custom-presenter](https://user-images.githubusercontent.com/603683/58083119-af7e4e00-7bb8-11e9-897b-a3ad7d1543a8.gif)

**Comment by jxnblk** [comment]
Thanks! This is a great idea! I was thinking of supporting this with Gatsby theme's shadowing feature in the next release, but I'll try to take a look at the PR in the next few days

**Comment by pomber** [comment]
I also have my own Presenter, this would be very useful.

**Comment by codepunkt** [comment]
@jxnblk any news on this?

**Comment by jxnblk** [comment]
Sorry, definitely wanna get this in, I just haven't had as much time to focus on mdx-deck recently. Hoping to go through this over the weekend, so hang tight 🙏
