### ISSUE TITLE
Non-root URL?

### ISSUE THREAD

**Issue by mtiller** [jxnblk/mdx-deck#368]
I was trying to upload some presentations to a site that serves them as static content.  But it seems that when I open the `index.html` file, it is black.  I then realized that if I hit right arrow, it goes to the second page and renders fine.  But I noticed that the URL in the address bar renders with a route that starts at the root.

Is there an obvious way to serve an `mdx-deck` generated deck from a non-root location so that a) the initial page renders and b) so that the URL in the browser is actually "correct" (i.e., if I sent it to somebody else, it would render).

I didn't see any command line argument to support this.

Thanks.

**Comment by jxnblk** [comment]
There's a (currently) undocumented `--basepath` flag that is passed to Reach Router. You should be able to use that for setting a custom basepath

**Comment by faogustavo** [comment]
I'm trying to use the basepath parameter, but every time I change to another page, another instance of the basepath is added to the URL.

### Example: 
* Base URL: `http://localhost:5000/android/`
* When navigating to the next page: `http://localhost:5000/android/android/1`

I'm using [serve](https://www.npmjs.com/package/serve) as server

**Comment by Goblinlordx** [comment]
This does not seem to be working at all... is there any way to get `basepath` working?
