### ISSUE TITLE
Custom syntax highlighting

### ISSUE THREAD

**Issue by janhesters** [jxnblk/mdx-deck#370]
I want to use [Darcula from react-syntax-highlighter](https://github.com/conorhastings/react-syntax-highlighter/blob/master/src/styles/prism/darcula.js) together with my own custom theme. But [since the `prism` key has been removed](https://github.com/jxnblk/mdx-deck/commit/8f2adc429ceedb0bb725db118ce9dffa172dcafa#diff-96197932eab46b6992f4f408131cad1dL79), I can't figure out how to do it.

```js
// theme.js
const custom = {
  colors: {
    text: '#abb7c4',
    background: '#2b2b2b',
  },
};

export { custom };
```

Here is what I try:

```js
import base from '@mdx-deck/themes/base';
import highlight from '@mdx-deck/themes/syntax-highlighter-prism';
import darcula from 'react-syntax-highlighter/styles/prism/darcula';
import { custom } from './theme';

export const themes = [base, highlight, custom, darcula];
```

But this doesn't work. How can you use custom syntax highlighting?

**Comment by jxnblk** [comment]
It’s probably best to provide your own `code` component, see https://github.com/jxnblk/mdx-deck/blob/master/docs/theming.md#syntax-highlighting

**Comment by janhesters** [comment]
@jxnblk So you mean using a custom `code` component, passing the prism style to it to wrap each line of code in it?

**Comment by jxnblk** [comment]
I mean create your own theme like this one and pass whatever custom colors/styles you want to itt https://github.com/jxnblk/mdx-deck/blob/master/packages/themes/syntax-highlighter.js
