### ISSUE TITLE
export PDF: component from first page printed on every page

### ISSUE THREAD

**Issue by alpinegizmo** [jxnblk/mdx-deck#371]
When I export to PDF, a component that's only used on the first page is being printed onto all other pages as well. This doesn't happen when the deck is served up by node, or when exported via yarn build, but only when exported to PDF via mdx-deck-export.

This is the component:

```
import * as ververica from './ververica'
export default props => (
    <div style={{
        display: 'flex',
        height: '150px',
        width: '100vw',
        position: 'fixed',
        bottom: 0,
        left: 0,
        alignItems: 'center',
        justifyContent: 'flex-end',
        background: ververica.white,
        zIndex: 10000,
  }}>
      <img
        src='/images/ververica.png'
        css={{
          marginRight: '30px',
          height: '100px',
        }}
      />
    </div>
)
```

**Comment by jxnblk** [comment]
It looks like you have `position: fixed` set, which will show in the same place relative to the viewport during the export. The path for print mode is `/print` if you want to debug with styles that don't use positioning

**Comment by alpinegizmo** [comment]
I was able to rework this branding element so that the position is relative, and now it only appears on the page(s) where it belongs. 

If is it the case that Components that have `position:absolute` or `position:fixed` will be printed on every page, perhaps the documentation should explain this somewhere. I find the overall page construction process is a bit mysterious still.

I'm closing this issue as there doesn't seem to be a real problem here.
