### ISSUE TITLE
Starting from defaults gives no transitions, no dot indicators, just a very basic xp

### ISSUE THREAD

**Issue by flq** [jxnblk/mdx-deck#373]
Basically, starting from the current settings renders quite differently to other decks seen out in te wild - when I look at them they don't seem to do anything special, yet they

* have transitions
* have dots on the bottom indicating the slide count

I tried to add transitions myself based on the react-pose sample for reach-router, but they die with the issue that the slides have no "key" prop set up.

So...what happened? Does the latest version not have those goodies anymore or what am I doing wrong?

**Comment by jxnblk** [comment]
v2 now uses Reach Router. I haven't looked into adding transitions with React Pose but it should be possible. The dot indicator was also removed but you can add your own using a custom Provider component
