### ISSUE TITLE
Flash of unstyled content

### ISSUE THREAD

**Issue by globophobe** [jxnblk/mdx-deck#378]
After building, in Safari and Firefox I see a FOUC when I change slides. The text is unstyled for a split second.

Theme is:
```
import { aspect } from '@mdx-deck/themes'
import highlight from '@mdx-deck/themes/syntax-highlighter-prism'

export const themes = [ aspect, highlight ]
```
No problem in Chrome.

**Comment by jxnblk** [comment]
I *believe* this is an issue with the aspect ratio component. Can you see if this still occurs without the `aspect` theme?

**Comment by globophobe** [comment]
Absolutely fine without the aspect theme.

**Comment by jxnblk** [comment]
Yeah, since the aspect ratio (currently) uses `ResizeObserver`, I think that's causing the styling to change after initial load – if anyone wants to work on a better solution, I'd be happy to look at a PR

**Comment by jxnblk** [comment]
Closing this since I think this is related to how `ResizeObserver` works in general
