### ISSUE TITLE
Serving presentation from subfolder 

### ISSUE THREAD

**Issue by andtos90** [jxnblk/mdx-deck#379]
I've built my last presentation with mdx-deck 2.3.2 and I just tried to serve it from my website on a subfolder: https://tosat.to/ha-slides/

As you can see when you load the presentation everything is black, if you change the slide using the arrow keys it loads as expected but the url is wrong:

#### Expected:
Something like `https://tosat.to/ha-slides/0`

#### Current behaviour: 
`https://tosat.to/0`

Presentation source code: https://github.com/andtos90/domotics/tree/docs/slides

This isssue is similar to  https://github.com/jxnblk/mdx-deck/issues/36.

**Comment by globophobe** [comment]
Try the —basepath flag. https://github.com/jxnblk/mdx-deck/issues/291

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andtos90** [comment]
Thanks @globophobe, with `--basepath` everything works as expected
