### ISSUE TITLE
Page Numbers

### ISSUE THREAD

**Issue by busypeoples** [jxnblk/mdx-deck#38]
An option to display the page numbers.

**Comment by jxnblk** [comment]
This makes me think that the [custom Provider](https://github.com/jxnblk/mdx-deck/#custom-provider) should maybe be inside the SlideDeck component and receive it's state as props – would open up a lot more flexibility in terms of customization

**Comment by busypeoples** [comment]
Yes, this would make a lot of sense!

**Comment by busypeoples** [comment]
It would be really interesting if we could define a <Footer> and <Header> via mdx that is applicable to all pages. For example always show a logo on the bottom right corner or a show a social media handle.
The `<dots />` component could be replaced by something else etc.

**Comment by jxnblk** [comment]
Yeah, I think the current Dots should probably move to a default Provider, then a custom Provider would need to add its own dots/progress bar/page numbers etc – starting with components will make it easier to support customization via front matter if that's something we decide to do
