### ISSUE TITLE
Stepper not showing

### ISSUE THREAD

**Issue by jordyvandomselaar** [jxnblk/mdx-deck#381]
I have the following markdown inside `deck.mdx`:

```markdown
# Page one

---

# Page two

---

# Page three
```

![mdx](https://user-images.githubusercontent.com/12712484/59878689-33d71300-93a9-11e9-94bd-85e6717a763d.gif)

As you can see it renders the slides but it doesn't render the current step at the bottom. Is this a bug or a setting I have to enable manually?

**Comment by jxnblk** [comment]
In v2, the dot indicator at the bottom was removed. You can add your own custom `Provider` to show UI like that – or if you want to wrap a custom `Provider` into a theme, I'd accept a PR

**Comment by jordyvandomselaar** [comment]
I'll close this as it's not an actual bug then =), thanks for the reply!
