### ISSUE TITLE
Append slide number at the end of url?

### ISSUE THREAD

**Issue by ZeningQu** [jxnblk/mdx-deck#384]
I tried to put a deck on a project's github page: [`https://zeningqu.github.io/choreography/`](https://zeningqu.github.io/choreography/)

When I navigate using ⬅️ ➡️ I noticed my url got shortened to [`https://zeningqu.github.io/0`](https://zeningqu.github.io/0) and [`https://zeningqu.github.io/1`](https://zeningqu.github.io/1)

Is there a way to preserve the `/choreography` project name and append the slide number to the end of the url?

**Comment by jxnblk** [comment]
There is a currently undocumented `--basepath` flag, which you should be able to use during build: `mdx-deck build deck.mdx --basepath="/choreography"`

**Comment by ZeningQu** [comment]
> `mdx-deck build deck.mdx --basepath="/choreography"`

Thank you very much! This worked for me! Closing the issue now.
