### ISSUE TITLE
HTML Document format

### ISSUE THREAD

**Issue by vestimir** [jxnblk/mdx-deck#39]
Right now the static output is semi-valid html document. 

```
<!DOCTYPE html>
<meta name='viewport' content='width=device-width,initial-scale=1'>
<style>*{box-sizing:border-box}body{font-family:system-ui,sans-serif;margin:0}</style>
<title>mdx-deck</title>
<div id=root></div>
<script src="main.js"></script>
```

This doesn't hints the browser about the encoding, which renders weird symbols. 

I'd like to achieve something more like:

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>mdx-deck</title>
  <style>*{box-sizing:border-box}body{font-family:system-ui,sans-serif;margin:0}</style>
</head>
<body>
    <div id=root></div>
    <script src="main.js"></script>
</body>
</html>
```

I see this comes from https://github.com/jxnblk/ok-mdx/blob/master/packages/ok-cli/lib/index.js#L55-L65

What's the idea behind skipping `<html>`, `<head>` and `<body>`. 

Should I open PR over ok-mdx with improvements for the template?

**Comment by jxnblk** [comment]
The `html`, `head`, and `body` tags are optional in HTML5, but that's not necessarily a great reason to leave them out. As far as the `utf-8` thing, that's definitely a bug that should be addressed

**Comment by vestimir** [comment]
I'm on it!

**Comment by vestimir** [comment]
Here you go :) 

https://github.com/jxnblk/ok-mdx/pull/8
