### ISSUE TITLE
Accessing theme to style custom components

### ISSUE THREAD

**Issue by HoverBaum** [jxnblk/mdx-deck#399]
Is there a way to define colors and other things in the theme and import it in components I am writing myself?

Would love to define primary colors and maybe base width for my slides to then use them throughout components so that I can build them into a package that people can style using their favorite colors.

**Comment by jxnblk** [comment]
There definitely is. The theming is now powered by https://theme-ui.com, so it might be helpful to check out the docs there. It’s not documented well at the moment, but also check out the `useDeck` hook, which should also have the theme in context: https://github.com/jxnblk/mdx-deck/blob/master/docs/api.md#usedeck

**Comment by HoverBaum** [comment]
Thanks for pointing me the right way. That works fine 🙂 

Only had to update my theme as well before it got through. Lots of changes to migrate to v3 😅 

I was thinking theme-uis `ThemeProvider` might also work but that gave me undefined. Sticking with `useDeck` seems like the way to go 👍
