### ISSUE TITLE
Routing seems broken, can't find 0.0.0.1

### ISSUE THREAD

**Issue by Irev-Dev** [jxnblk/mdx-deck#405]
When I try to go to the next slide (with space or arrow right) it appears to be trying to go to `1` instead of `/1` perhaps?
The demo link for this repo seems to be effected too.
Might be related to the recent major version release as I rolled back to 2.5.1 and it's working fine.

I'd be happy to dig into this if you'd like me to. But can't right now.

![2019-07-19 14 29 06](https://user-images.githubusercontent.com/29681384/61509418-ad5a3380-aa31-11e9-859f-998da931b5c8.gif)

The mdx file
```
# first slide
when I hit space I get saddness

---

# slide 2
I can get here manually though
```
scripts section in package.json
```
"scripts": {
    "start": "mdx-deck ./src/deck.mdx"
  }
```

**Comment by jxnblk** [comment]
Thanks! This looks like a regression from one of the recent PRs – I'll dig in and see if I can patch this

**Comment by linonetwo** [comment]
Can you release it?

**Comment by jxnblk** [comment]
`v3.0.7` should have the fix

**Comment by Irev-Dev** [comment]
Thanks @jxnblk
