### ISSUE TITLE
Can't use Component Shadowing

### ISSUE THREAD

**Issue by alpinegizmo** [jxnblk/mdx-deck#408]
I can't seem to get component shadowing to work, which is a shame, as this is a major part of my motivation for upgrading to v3.

https://github.com/alpinegizmo/mdx-deck-v3-static has an attempt to shadow the Slide component. In v2 I was able to get the slides to be left aligned by doing this (among other things) in my custom theme:

```
  Slide: {
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    marginLeft: 0,
    paddingLeft: `calc((100vw - ${slideWidth}) / 2)`,
    top: 0,
    '& > div': {
      minWidth: slideWidth,
      maxWidth: slideWidth,
      minHeight: slideHeight,
      maxHeight: slideHeight,
    },
  },
```

and I'm trying to reproduce this in v3.

So far my shadow component is being completely ignored.

**Comment by pomber** [comment]
Are you using the mdx-deck cli? 
I think component shadowing only works if you [use it from a gatsby site](https://github.com/jxnblk/mdx-deck/blob/master/docs/gatsby.md).

**Comment by alpinegizmo** [comment]
I've succeeded in getting this to work, so I'm closing this now. The key step was indeed getting mdx-deck v3 working in a gatsby site. The rest was straightforward enough.
