### ISSUE TITLE
Can't Install MDX-DECK

### ISSUE THREAD

**Issue by Athul-CA** [jxnblk/mdx-deck#410]
Whenever  I run `npm i -D mdx-deck`, I'm getting an Error Like this,
```
npm i -D mdx-deck          
npm ERR! Unexpected end of JSON input while parsing near '...,"webpack-configurato'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/athul/.npm/_logs/2019-07-21T03_57_59_235Z-debug.log
```
I had been using MDX-DECK for a while but upgraded it from Version 1.6 to 3.0.6 yesterday, It didn't work then so I was trying to reinstall the smae then caught up with this error

**Comment by sibelius** [comment]
try to use yarn

**Comment by Athul-CA** [comment]
Thanks @sibelius it worked using yarn. @jxnblk love the new updates ❤️
