### ISSUE TITLE
Issue getting started with basic MDX file and mdx-^3.0.7

### ISSUE THREAD

**Issue by SeanKilleen** [jxnblk/mdx-deck#420]
Hi all,

Having some issues with mdx-deck and posting here in the hopes that I can also post a solution when I have one, or that someone will beat me to it.

## Repro Steps

* Basic `npm init` 
* `npm i -D mdx-deck` (sets the dependency to `^3.0.7`
* Create `presentation.mdx` with the following content:

```
# This is the title of my deck

---

# About Me

I'm Sean!

---

Just some text

---


# The end
```

* Create a `start` script that calls `mdx-deck presentation.mdx`
* Run `npm install`
* Run `npm run start`

**Expected Behavior**: See the presentation deck run 

**Actual Behavior**: See the following output

```
 ERROR #98123  WEBPACK

Generating SSR bundle failed

Unexpected token (10:4)

File: ..\@mdx-deck\themes\dots.js:10:4


 ERROR #98123  WEBPACK

Generating SSR bundle failed

Unexpected token (11:9)

File: ..\@mdx-deck\themes\syntax-highlighter-prism.js:11:9


 ERROR #98123  WEBPACK

Generating SSR bundle failed

Unexpected token (17:9)

File: ..\@mdx-deck\themes\syntax-highlighter.js:17:9
```

## Versions

* mdx-deck: ^3.0.7
* node: -v: 10.16.0
* npm -v: 6.3.0

**Comment by jxnblk** [comment]
Possibly related to #416

**Comment by SeanKilleen** [comment]
Ah, sorry I missed it! It's absolutely related. Closing this as a duplicate in favor for that.
