### ISSUE TITLE
useDeck and mdx-deck v3

### ISSUE THREAD

**Issue by pvinis** [jxnblk/mdx-deck#426]
How do I import `useDeck`?
Do I need `@mdx-deck/components`?

**Comment by pvinis** [comment]
ok found it, its `import { useDeck } from 'gatsby-theme-mdx-deck'`, which is weird.

**Comment by jxnblk** [comment]
Looks like you found it. The entire application and all components are built into `gatsby-theme-mdx-deck` now – you can sort of think of it as a component library that also generates the pages needed for the decks in Gatsby. All modules should also be exported from `mdx-deck` as well, if you're using the CLI on its own
