### ISSUE TITLE
Can't use `Image` inside `Split`

### ISSUE THREAD

**Issue by pvinis** [jxnblk/mdx-deck#429]
It just doesn't render.

**Comment by jxnblk** [comment]
The `Image` component is for rendering a background image for the entire slide. I'm guessing it's rendering with messed up styles inside of `Split` If you want an image side-by-side with other content, either use `![alt](image.png)` or the `<img />` tag in `Split`

**Comment by pvinis** [comment]
I did try with `![](images/my.png)` but it rendered a blue question mark, so I wasn't sure what the problem is there..

**Comment by HoverBaum** [comment]
This could well be related to #401, about static assets (such as images) not being picked up and hosted.

**Comment by jxnblk** [comment]
Duplicate of #401
