### ISSUE TITLE
"Page not found" errors in terminal

### ISSUE THREAD

**Issue by bchiang7** [jxnblk/mdx-deck#436]
Hello! With a fresh install of `v3.0.9` I'm getting errors in my terminal saying pages are not found. For example:

```
Error loading a result for the page query in "/0". Query was not run and no Page not found /0
```

<img width="922" alt="Screen Shot 2019-08-11 at 11 37 23 PM" src="https://user-images.githubusercontent.com/6599979/62845223-58a68300-bc94-11e9-80cf-cc45d6d9032c.png">

And subsequently, this causes two console errors to appear when navigating to each slide when deployed to a platform like Netlify (one for 404.html, and one for the slide's page)

<img width="458" alt="Screen Shot 2019-08-12 at 12 03 36 AM" src="https://user-images.githubusercontent.com/6599979/62845286-c81c7280-bc94-11e9-8468-9c67c3db9b64.png">

CodeSandbox link: https://codesandbox.io/embed/mdx-deckprovider-example-cd8ey

This seems like an issue with setting up routes with Gatsby. Anyone have any ideas on how to resolve this issue? Thanks in advance!

**Comment by alpinegizmo** [comment]
+1 Troubled by this too.

**Comment by Rahmon** [comment]
Same here and I can't export to pdf or html/js (build). Both are outputted just with a blank page.

**Comment by jxnblk** [comment]
Thanks! Can you provide more details about your setup, npm (or yarn) versions, node version, and dependencies in your package.json?

**Comment by bchiang7** [comment]
## Local setup

node: `10.13.0`
npm: `6.10.1`
package.json dependencies:
```json
"devDependencies": {
  "mdx-deck": "^3.0.9"
}
```

## Page not found errors

After doing some investigating, the `Page not found` errors I was previously seeing aren't appearing anymore after removing my `yarn.lock`/`package-lock.json` and doing a fresh `yarn/npm install` (I tried both `npm` and `yarn` to see if there was a difference)  

I'm guessing there was some weird `node_modules` caching issue, but I'm still seeing the page not found query errors in this codesandbox link if you fork it: https://codesandbox.io/embed/mdx-deckprovider-example-cd8ey
```
Error loading a result for the page query in "/1". Query was not run and no
Page not found /1
```

## Netlify page-data.json 404 errors

Furthermore, the `page-data.json` 404 errors when deployed to Netlify seem like a result of hosting a static gatsby site with client-side routing to Netlify. 

I found this article https://dev.to/dance2die/page-not-found-on-netlify-with-mdx-deck-4h9d which led me to adding a `netlify.toml` to the root of my project with the following

```toml
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```

Adding `redirects` have fixed the 404 errors 🎉 

## Fixes

### `Page not found` errors in terminal

Removing lock file and doing a fresh `npm/yarn install`

### `/page-data.json` 404 errors on Netlify

Adding a `netlify.toml` file with

```toml
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```
