### ISSUE TITLE
SSR bundle failures

### ISSUE THREAD

**Issue by josefaidt** [jxnblk/mdx-deck#437]
ref, https://codesandbox.io/s/mdx-deck-babel-error-9xs6t

Having issues with a theme I just updated to support v3. Running with the local copy in a monorepo is fine, same as deploying it to Now from the monorepo root. But I cannot run locally with a copy from npm. Errors are happening at the position at which JSX begins.

![image](https://user-images.githubusercontent.com/5033303/62891596-b629e680-bd0b-11e9-9e55-904162484b2d.png)

This actually started happening last week and I assumed it was due to the v3 upgrade, however after migrating to use ThemeUI and update a few components I am presented with these same errors.

**Comment by josefaidt** [comment]
I was able to reproduce in CodeSandbox, https://codesandbox.io/s/mdx-deck-babel-error-9xs6t

**Comment by josefaidt** [comment]
FWIW I've attempted linking it with `yarn link` and get an error in a file that doesn't exist, which I found a bit odd.
![image](https://user-images.githubusercontent.com/5033303/62943188-85938c80-bd9f-11e9-9df4-7ac53bd59b52.png)

**Comment by jxnblk** [comment]
Thanks! I've never managed to get `yarn link` to work with Gatsby themes personally, so I'd suggest avoiding that if possible. Have you tried wiping out the lock files and doing a fresh install? And, are you compiling the source code in your own theme? I don't think MDX Deck will automatically parse JSX in node modules like that

**Comment by josefaidt** [comment]
Using `yarn link` was a last ditch effort before pulling my deck theme into a monorepo to write my talk. I have tried that, and in a fresh CodeSandbox instance to get information from a "pure" standpoint.

I am not compiling the source code in my theme, I didn't have to do this in the past (although the functionality may have been unintended using that method). Is compiling the source code a recommended step? To your last point, I think that is exactly what is happening.

**Comment by jxnblk** [comment]
If your theme module is local to where the mdx-deck cli is running, it should compile jsx and es6, but if you're installing from npm, then yeah, it'll need to be compiled with something like Babel – if that did work in previous versions, that's news to me :)

**Comment by josefaidt** [comment]
Ah that makes sense. It's fine in a monorepo, which I guess would also be considered as being local. I will certainly try compiling and report back soon!

**Comment by josefaidt** [comment]
That did it! Don't know what I was thinking not building before, but with a quick [babel file](https://github.com/josefaidt/mdx-deck-theme-garlic/blob/master/theme/.babelrc) and a prepublish build script seemed to work. Thanks for the assistance!
