### ISSUE TITLE
Where are the bullets/dots on the bottom?

### ISSUE THREAD

**Issue by ravanscafi** [jxnblk/mdx-deck#494]
Sorry, this might be a noob question, but I'm trying to use mdx-deck and my slides, even with themes, doesn't have the bullets on the bottom. (Neither some transitions when changing the slide)

Am I missing something? I took a look at the config and found nothing.

Are these screenshots outdated?
![](https://raw.githubusercontent.com/jxnblk/mdx-deck/master/docs/images/yellow.png)

Thanks!

**Comment by netochaves** [comment]
I'm with the same problem, you solved this?

**Comment by ravanscafi** [comment]
> I'm with the same problem, you solved this?

Not yet @netochaves

**Comment by josefaidt** [comment]
It was a part of the default provider that was removed in v2: https://github.com/jxnblk/mdx-deck/issues/350#issuecomment-487329483

You can roll your own by tapping into the deck state with `useDeck` and accessing `length` and `index`

**Comment by johnletey** [comment]
@josefaidt Is there anyway to add a progress indicator? Like a solid bar that increases in length per slide?

**Comment by ravanscafi** [comment]
Thanks @josefaidt :)

**Comment by Relequestual** [comment]
@ravanscafi I’m guessing that means you figured this out?

If so can you share your solution?

**Comment by ravanscafi** [comment]
@Relequestual, I'm using v1.10.2 right now.
https://github.com/ravanscafi/mongodb-workshop/blob/master/package.json#L12

**Comment by nraw** [comment]
@josefaidt sweet!
It doesn't allow for clicking on a part to jump to that slide though, correct? That was probably one of the two use cases I have with the bullets.
Is there a good way to find mdx deck themes out there besides the ones listed in this repo?

**Comment by josefaidt** [comment]
@nraw I suppose you could add a click action to each of your bullets and Link out to the slide, should be able to pull the `<Link/>` component from reach router.

Typically I've found they'll follow the `mdx-deck-theme` naming convention

**Comment by micheleb** [comment]
in case anyone finds this issue while using v4 like me, note that you can no longer specify a custom `Provider`, unfortunately.

You now need to use the `<Footer>` component instead. [This](https://github.com/micheleb/rn4android-slides/blob/master/ProgressBar.js) is how I implemented a progress bar for my slides, and I included it by adding this at the top of my `deck.mdx`:

```jsx
import { ProgressBar } from "./ProgressBar";

<Footer>

<ProgressBar />

</Footer>
```
