### ISSUE TITLE
Add built-in layout components

### ISSUE THREAD

**Issue by jxnblk** [jxnblk/mdx-deck#50]
Layout components can be used to change the look of a single slide, similar to templates in other presentation apps. Some built-in layouts could work with the current theme to invert colors and make other small style adjustments.

Example:
```mdx
export { yellow as theme } from 'mdx-deck/themes'

# Normal Slide

---
export { Invert as default } from 'mdx-deck/layouts'

# Slide with Layout
```

**Comment by tomByrer** [comment]
Maybe seperate repos?  Just don't want too much code bloat for layouts that aren't used everytime.
