### ISSUE TITLE
Webpack error when using Image component

### ISSUE THREAD

**Issue by lorensr** [jxnblk/mdx-deck#525]
When I add `import { Image } from '@mdx-deck/components'`, I get an error:

```
 ERROR #98123  WEBPACK

Generating SSR bundle failed

Can't resolve '@mdx-deck/components' in '/Users/me/node_modules/mdx-deck/.cache/caches/gatsby-plugin-mdx/mdx-scopes-dir'

File: .cache/caches/gatsby-plugin-mdx/mdx-scopes-dir/63c34dbe1fc36c01040121adb27312d6.js

⠸ start webpack server
TypeError: util.getSystemErrorName is not a function
    at getCode (/Users/me/node_modules/execa/lib/error.js:11:16)
    at makeError (/Users/me/node_modules/execa/lib/error.js:50:35)
    at handlePromise (/Users/me/node_modules/execa/index.js:112:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by lorensr** [comment]
I've tried installing `@mdx-deck/components` both locally and globally

**Comment by schaab** [comment]
@lorensr I have run across this error using `Split`. Counter intuitive, but removing the import and just using the component fixes.

**Comment by lorensr** [comment]
That works, thanks! Guess docs need updating

**Comment by schaab** [comment]
Not sure. Seems odd that you wouldn't import it. If you are using `3.0.13` the way you are [importing is deprecated](https://github.com/jxnblk/mdx-deck/blob/f9bc2456ff233157c74d5f9e0029eff25417f11b/MIGRATION.md)

**Comment by qjcg** [comment]
FYI, I created PR #527 that updates the docs & examples to use the v3 package names.

**Comment by qjcg** [comment]
@jxnblk now that PR #527 has been merged and the docs have been updated, I think this issue can be closed.
