### ISSUE TITLE
How to disable space to go to next slide?

### ISSUE THREAD

**Issue by franreysaycon** [jxnblk/mdx-deck#526]
I want to do a live coding using mdx-deck-react-live.
However space is causing to go to the next slide.
How do I opt-out of this behavior?

**Comment by jxnblk** [comment]
You could probably use `e.stopPropagation()` on your react-live component to prevent mdx-deck from picking it up

**Comment by franreysaycon** [comment]
Hey @jxnblk thanks for the reply. I decided to just use React Live instead of mdx-deck-react-live. 
awesome work btw, gatsby integration works really nice. check it out fsaycondev-react-native-a-tutorial.netlify.com
