### ISSUE TITLE
custom Webpack loaders support in v3/eject command not working?

### ISSUE THREAD

**Issue by jebeck** [jxnblk/mdx-deck#585]
The migration doc says this:

> The standalone CLI has been rewritten with Gatsby, and the following CLI flags are no longer supported:
--webpack - use the Gatsby theme directly to customize webpack features

...but it's unclear to me what "use the Gatsby theme directly" means, as none of the Gatsby files are exposed in an mdx-deck repo. (I have used Gatsby directly before.)

I did a `mdx-deck --help` and saw there was an `eject` command, so I tried that, but it doesn't seem to work/didn't do anything. And I see that's an issue that's already been filed: #511 

In case it's additionally useful, here's the output from my attempt:

```
[mdx-deck] ejecting Gatsby site
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1530k    0 1530k    0     0  1189k      0 --:--:--  0:00:01 --:--:-- 1189k
npm WARN code-surfer@3.0.0-beta.1 requires a peer of mdx-deck@3.0.10 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-plugin-react-helmet@3.1.13 requires a peer of react-helmet@^5.1.3 but none is installed. You must install peer dependencies yourself.
npm WARN react-flatland@0.0.0-alpha.3-b5c2d430 requires a peer of tsne-js@* but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.

audited 44642 packages in 8.824s
found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
git version 2.20.1 (Apple Git-117)
Reinitialized existing Git repository in /Users/janabeck/GitHub/flatland/.git/
On branch take-three-ejected
nothing to commit, working tree clean
[err] { Error: Command failed: git commit -am "Init"
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at gitInit (/Users/janabeck/GitHub/flatland/node_modules/initit/index.js:26:3)
    at create (/Users/janabeck/GitHub/flatland/node_modules/initit/index.js:81:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 64272,
  stdout: null,
  stderr: null }
```

Am I correct in assuming that `eject` is the first step towards adding a custom Webpack loader? If so, it might be worth amending the migration instructions and/or README to make that a little clearer; happy to do this if you agree!

**Comment by jxnblk** [comment]
> use the Gatsby theme directly to customize webpack features

See https://github.com/jxnblk/mdx-deck/blob/master/docs/gatsby.md for docs on how to use the theme with Gatsby. From there, you can use Gatsby's APIs to adjust the webpack config

**Comment by jebeck** [comment]
Closing this as it's no longer relevant to me. My epic tale of slide deck build problems isn't worth your time, so I'll just save us both and close it :)
