### ISSUE TITLE
Suggestion: contain default layout

### ISSUE THREAD

**Issue by trevordmiller** [jxnblk/mdx-deck#602]
Currently if you have a large amount of content on the screen (like in the example below with markdown code blocks) there isn't padding or containment in the default layout - so the content overflows and runs to the edge of the screen. IMO it would be nice to add containment and padding so that the content doesn't hit the edge of the viewport.

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/5497885/70575663-38180800-1b64-11ea-8cb2-7e93d09d2f88.png">

Here is the example slide code used to render this:

```
## Some markdown

\`\`\`rust
pub fn add(a: i32, b: i32) -> i32 {
    a + b
}

// This is a really bad adding function, its purpose is to fail in this
// example.
#[allow(dead_code)]
fn bad_add(a: i32, b: i32) -> i32 {
    a - b
}

#[cfg(test)]
mod tests {
    // Note this useful idiom: importing names from outer (for mod tests) scope.
    use super::*;

    #[test]
    fn test_add() {
        assert_eq!(add(1, 2), 3);
    }

    #[test]
    fn test_bad_add() {
        // This assert would fire and test will fail.
        // Please note, that private functions can be tested too!
        assert_eq!(bad_add(1, 2), 3);
    }
}
\`\`\`
```

**Comment by trevordmiller** [comment]
Currently I'm using this as a workaround:

## index.mdx

```mdx
import customTheme from "./utils/customTheme";

export const themes = [customTheme];
```

## customTheme.js

```js
const customTheme = {
  styles: {
    Slide: {
      padding: "0 10%"
    }
  }
};

export default customTheme;
```

**Comment by jxnblk** [comment]
The previous version used to have padding, but required negative margins for some of the fullscreen layout components. This version tries to be less opinionated with styles. I think adding custom styles as you have them in your theme is a-okay.
