### ISSUE TITLE
Move default Dots to a default Provider component

### ISSUE THREAD

**Issue by jxnblk** [jxnblk/mdx-deck#62]
When setting a custom provider, users will need to add their own progress indicators

**Comment by busypeoples** [comment]
Can they import the Dots specifically and remix with other components?

**Comment by jxnblk** [comment]
Think I'm going to take a stab at this along with #6 in a single PR

**Comment by busypeoples** [comment]
Ok, I can try to work on https://github.com/jxnblk/mdx-deck/issues/63 if that makes sense.

**Comment by jxnblk** [comment]
Yeah, if you want to go for it!
