### ISSUE TITLE
Uncaught TypeError: Cannot read property 'originalType' of undefined

### ISSUE THREAD

**Issue by alhansrisuk** [jxnblk/mdx-deck#624]
Having an issue with using built in layouts when compiling to the web:
![image](https://user-images.githubusercontent.com/194897/72171372-d506d480-33a0-11ea-9bc3-80b2378a8ada.png)

Here is my `deck.mdx`:
```jsx
import { themes, Split } from 'mdx-deck'
import { CodeSurfer } from 'code-surfer'
import { nightOwl } from '@code-surfer/themes'

export const theme = themes.dark

<Split>
Test
</Split>
---
# SLIDE 2 - HEADERS

## Header 2
### Header 3
#### Header 4
##### Header 5

---
```

**Comment by jxnblk** [comment]
Not sure if this would cause the issue, but `---` needs empty newlines above and below to register as an `<hr>` in markdown syntax

**Comment by alhansrisuk** [comment]
@jxnblk this fixed it!!
