### ISSUE TITLE
Serving built output leads to 404 on routes

### ISSUE THREAD

**Issue by trevordmiller** [jxnblk/mdx-deck#625]
Steps to reproduce:

- Follow the [Getting Started](https://github.com/jxnblk/mdx-deck#getting-started) guide.
- Run `mdx-deck build deck.mdx`.
- Serve the built `public` directory. For example, `npx serve public`. I reproduced with an nginx host as well.
- Navigate to a slide other than the starting point, for example the second slide (`/1`).
- Refresh the page. You'll see a 404.

**Comment by jxnblk** [comment]
Are you using `gatsby serve` for this? I'm not sure if your setup would handle the client-side routing the way that Gatsby might expect...

**Comment by trevordmiller** [comment]
Good point! I was not aware of `gatsby serve`. Will try that. Was able to get it working in nginx with config like this to re-route:

```
location / {
    try_files $uri $uri/ /index.html;
}
```

**Comment by pedroapfilho** [comment]
Hi! I don't know why this issue was closed. I still don't know how to handle the `404s` when reloading on a route.

**Comment by trevordmiller** [comment]
I would suggest that @jxnblk update mdx-deck docs to link to some Gatsby docs that explain this for those who run into it in the future. But the gist is that Gatsby is a SPA setup so if a server serves  it, a rewrite type rule is needed so that `url}/number` goes back to the root. In my case, I did this with [some nginx config](https://github.com/jxnblk/mdx-deck/issues/625#issuecomment-574303071). If you were using another tool like `serve` you could do this with config like https://github.com/zeit/serve-handler#rewrites-array.

**Comment by pedroapfilho** [comment]
Thanks @trevordmiller! I'll check it out!

**Comment by imyelo** [comment]
How about providing a config field that we can switch the router mode to [hash router](https://reacttraining.com/react-router/web/api/HashRouter)? That will be perfect for a pure static file server in JAMStack likes GitHub Pages.
