### ISSUE TITLE
Video plays one slide early in presentation mode

### ISSUE THREAD

**Issue by alexd99** [jxnblk/mdx-deck#642]
In my slide deck, I have a video component with autoplay set to true on slide 3. When I open presentation mode and navigate to slide 2 the video in slide 3 is rendered in the preview pane of the presentation mode, and plays. I did not expect this to happen because the video is still one slide away from being the active slide. 

I'm not sure if this is another use case for a video player component as described in this [issue](https://github.com/jxnblk/mdx-deck/issues/4).

Here is a minimal reproduction of this issue:
[video-autoplay.zip](https://github.com/jxnblk/mdx-deck/files/4171766/video-autoplay.zip)

This problem also occurs in the overview mode.

Thank you for this project and for all the great work you are doing!

**Comment by jxnblk** [comment]
Is this a custom `Video` component? I think it'll need to use some of MDX Deck's internal state to know which slide is *active*

**Comment by alexd99** [comment]
I am using the native video element to produce this bug. 

There is an issue discussing if a custom video component should be added to this library. I was wondering if this bug was another reason that this custom video component should be made.

**Comment by jxnblk** [comment]
This sounds like expected behavior for the `<video>` element -- the preview of the next slide isn't a special HTML element, and the `<video>` element is not going to be aware of the React application's state. A custom component *could* help with this, but that's not part of this library's API

**Comment by alexd99** [comment]
Ok, that makes sense I will go ahead and close this card.

**Comment by karlhorky** [comment]
Based on [my original approach](https://github.com/jxnblk/mdx-deck/issues/4#issuecomment-470180791), this seems to work in `mdx-deck@4.1.1`:

```mdx
import screencapture from './screencapture.mp4';

<div
  dangerouslySetInnerHTML={{
    __html: `
      <video
        style="max-width: 80%"
        controls
        autoplay
        muted
        src="${screencapture}"
      />
    `,
  }}
/>
```
