### ISSUE TITLE
Stylesheet escape hatch

### ISSUE THREAD

**Issue by jasonbarry** [jxnblk/mdx-deck#643]
What's the easiest way to add CSS rules the parent of the Slide component, for example? Or add a `<style>` tag to the document head?

**Comment by jasonbarry** [comment]
aaaaaand clearly it's the `<Head>` component. My b.

**Comment by jxnblk** [comment]
I'd recommend using the built in [theming API](https://github.com/jxnblk/mdx-deck/blob/master/docs/theming.md) if possible, or Emotion's `Global` component if absolutely necessary
