### ISSUE TITLE
Available Themes Doc

### ISSUE THREAD

**Issue by btoles** [jxnblk/mdx-deck#699]
https://github.com/jxnblk/mdx-deck/blob/master/docs/themes.md

All of the examples are missing the `@` for the `mdx-deck` scope.

**Comment by giovannimariacusaro** [comment]
@btoles and others things 🤔 https://github.com/jxnblk/mdx-deck/issues/677#issue-586534612

**Comment by cspeterson** [comment]
"other things" aside 🙂 I made a pull request for the themes docs #729
