### ISSUE TITLE
Still supported/maintained?

### ISSUE THREAD

**Issue by baileydoestech** [jxnblk/mdx-deck#765]
Owing to the lack of recent commits and increasing number of PR's, is this going to be supported/maintained going forward?

Activity of the main contributor seems to have tailed off (looks like he may now be at Gatsby) so would like to know if its worth looking at alternatives (unfortunately doesn't seem to be many).

**Comment by maxammann** [comment]
I think there are none which support mdx. But maybe the code which is involved to create slide shows in react is not much. Maybe a simple react library + webpack would be enough compared to this. What do you think?

**Comment by spences10** [comment]
I've found some good alternatives (IMO), I've detailed them in [here], this issue gets a mention as well actually! Meta!!

[here]: https://scottspence.com/2021/02/16/making-mdx-presentations/

**Comment by karlhorky** [comment]
Is there anyone who would be open to take over the role of maintainer here? If there is a clear person / group of people who would do this, it may be something that @jxnblk would consider handing over...

**Comment by ulisesantana** [comment]
I really like mdx-deck and I want this tool to be improved, so I'm open to take over the role of maintainer.

**Comment by Nezteb** [comment]
Other options to consider:
- https://github.com/FormidableLabs/spectacle
	- [Supports JSX and MDX](https://formidable.com/open-source/spectacle/docs/#jsx).
- https://github.com/marp-team/marp
	- [No MDX support though](https://github.com/orgs/marp-team/discussions/177#discussioncomment-1414613).
- https://github.com/hiroppy/fusuma
	- Which @spences10 mentions in his blog post.

**Comment by karlhorky** [comment]
@Nezteb Thanks for the reminder about Spectacle! I've opened an issue to ask about moving away from `create-react-app` and to Next.js:

- https://github.com/FormidableLabs/spectacle/issues/1260

**Comment by karlhorky** [comment]
As of `spectacle@10.0.0`, the Next.js App Router is supported and documented:

- https://github.com/FormidableLabs/spectacle/pull/1263

So maybe this is the most modern, maintained option for moving away from `mdx-deck`

**Comment by karlhorky** [comment]
Oh looks like @cpojer just created a minimalist slide deck framework called ReMDX based on a lean fork of Spectacle 👀🔥

- https://twitter.com/cpojer/status/1664603891219173376
- https://github.com/cpojer/remdx
