### ISSUE TITLE
Last slide behavior

### ISSUE THREAD

**Issue by vestimir** [jxnblk/mdx-deck#77]
Currently, once you reach the last slide and push next, the presentation goes to the very first slide. 

Maybe it makes more sense to loop endlessly (so when you are on the first slide, you can quickly go back to the last by pushing left). 

What do you think?

**Comment by tomByrer** [comment]
Use case:
if the talk is over, you looped back to first slide (for title & speaker name/contact info), but someone in the Q&A asks something that a later slide covers.

**Comment by vestimir** [comment]
Yep, travelling back and forth can bring more flexibility. 

I'll propose PR over the weekend.

**Comment by jxnblk** [comment]
I feel like it's a little more "dangerous" to accidentally go to the last slide from the beginning when presenting, and that was the thinking for not allowing that to happen. But after looking at how other presentation apps work, I don't think the endless loop behavior makes sense to have in this library at all. You can currently jump to any slide using the dot indicators or with grid mode (`opt+g`), which I think are better ways to go to a specific slide
