### ISSUE TITLE
Is there a way to run custom javascript on deck load and slid transitions ?

### ISSUE THREAD

**Issue by tjtaill** [jxnblk/mdx-deck#772]
Hi sorry for a basic questions I want to give a talk/demo about snowplow analytics  https://docs.snowplowanalytics.com/docs/getting-started-on-snowplow-open-source/what-is-snowplow-open-source/ and it would be neat if I could embed the snowplow javascript tracker  https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-tracker/ in the presentation itself so it tracks the page views of the presentation. I read something about custom mdx provider but maybe there is an easier way with callbacks or react hooks ?

Anyways any pointers you could provider would be greatly appreciated.

**Comment by ChristianMurphy** [comment]
mdx-deck provides a [`useDeck` hook](https://github.com/jxnblk/mdx-deck/blob/master/docs/api.md#usedeck) which can be used to observe the slide show state and could likely be used to call a function on state/slide/step change.

**Comment by tjtaill** [comment]
I notice there isn't to any docs or examples on how to use useDeck. Even reading the source code is not very insightful but still it is more than I had before thanks

**Comment by tjtaill** [comment]
In the end I wound up doing this

<div style="display: none">{pageView()}</div> where pageView wrapped the other function to return null, undefined or something renderable it works
