### ISSUE TITLE
Can't resolve 'mdx-deck/themes'

### ISSUE THREAD

**Issue by ptimson** [jxnblk/mdx-deck#774]
I can't seem to use the latest build (4.1.1) with `mdx-deck/themes` I get a webpack error:

```
 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'mdx-deck/themes' in '/sandbox'
```

Even using the example codesandbox here:
https://codesandbox.io/s/github/jxnblk/mdx-deck/tree/master/examples/themes

Any ideas of a previous version where things are working!

**Comment by ptimson** [comment]
I gave up with this and found an alternative.

Using Reveal.js with Hugo: https://themes.gohugo.io/reveal-hugo/

You can write your slides in Markdown. It's the best I could find that is close to this lib and I think it's great!

**Comment by pgollangi** [comment]
You should change theme usage to below:
```js
import { themes } from 'mdx-deck'
export const theme = themes.future
```
from 
```js
export { future as theme } from 'mdx-deck/themes'
```
https://github.com/jxnblk/mdx-deck/blob/master/docs/theming.md
