### ISSUE TITLE
Open new window button in presenter mode

### ISSUE THREAD

**Issue by jxnblk** [jxnblk/mdx-deck#81]
In presenter mode, there should be a button that opens a new window (that's not in presenter mode) that can be used to display the audience.

**Comment by jforaker** [comment]
i don't wanna open an issue so I'll drop my suggestion here: 
**Idea**: would be cool to have a "viewer" mode where navigating through slides is disabled for viewers and only enabled for presenter.
**Use case**: sharing a link during a remote meeting and not wanting viewers to interrupt your presentation
**Result**: when a presenter tab is open (and has an optional flag perhaps `?disable=true` or something), viewer tabs are disabled from navigating
