### ISSUE TITLE
Custom theme not working?

### ISSUE THREAD

**Issue by rchrdnsh** [jxnblk/mdx-deck#92]
Trying to make a custom theme, but it's not working, but without a clear error message, so I'm not sure what I'm doing...

```javascript
import { theme } from 'mdx-deck/themes'

export default {
  ...theme,
  font: 'Roboto, sans-serif',
  colors: {
    text: 'black',
    background: 'white',
    link: 'black',
  },
  css: {
    fontSize: 'calc(16px + 6 * ((100vw - 320px) / 680))',
    textAlign: 'left'
  }
}

# Yo!

This is my first mdx-deck slide.

---

# Hey!

This is my second.

---
```

and I get a blank page with some vague (at least to me) error messages in the console:

<img width="1440" alt="screenshot 2018-08-08 16 03 27" src="https://user-images.githubusercontent.com/7884263/43870524-c6b3fb78-9b2c-11e8-848d-14b2d3047cbc.png">

sooooooo...don't know what I'm doing wrong here, so any help would be appreciated :-)

**Comment by rchrdnsh** [comment]
nvrmnd, I did not realize that it was supposed to be a separate file.

**Comment by jxnblk** [comment]
MDX treats `default` exports as layouts. To set a theme with mdx-deck, you'll want to export a `theme` – it should work if you have it inline, but ymmv
