### ISSUE TITLE
Prevent tabs from changing the slide

### ISSUE THREAD

**Issue by kentcdodds** [jxnblk/mdx-deck#93]
If you go to [this deck](https://simply-react.netlify.com) and just lay on the <kbd>tab</kbd> key, you'll see it focuses the next element which advances the slideshow. I'd prefer the current slide to capture the tab and loop it back as if the current slide is all that's on the page.

**Comment by jxnblk** [comment]
Took at stab at trying to quickly fix this in the `focus-trap` branch, but running into issues with how existing libraries work – might need a bespoke solution for mdx-deck to handle this

**Comment by jxnblk** [comment]
Just published v2 beta, which now uses Reach Router, and *should* resolve this issue. Feel free to give it a shot with `npm i mdx-deck@next`
